### ISSUE TITLE
comma on numpad isn't recognized

### ISSUE THREAD

**Issue by haenschen** [stsp/dosemu2#171]
Hi,

as the title says the numpad comma is not recognized for me on Ubuntu either with dosemu or dosemu -S. It just does nothing (in DOS prompt).
The other comma works fine.

**Comment by haenschen** [comment]
Correction: It is working as the alternate keybind, "delete". Doesn't matter which numlock state.

**Comment by haenschen** [comment]
Okay I bisected this as pre4 is working fine but it won't let me compile if I try to revert this commit from devel.

```
e7d243b081ad548c0eaa4168eeb0146f44c5afe5 is the first bad commit
commit e7d243b081ad548c0eaa4168eeb0146f44c5afe5
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Thu Sep 17 14:32:58 2015 +0300

    move static config bits from autoconf to dosemu_config.h

:100644 100644 63363d27c202a141989517b6ac677ef390cf77df 2164b3087cf82c35316a31db33dc31af23fddbf0 M	configure.ac
:040000 040000 ea756313c86b4b206455216ce4af1043de1a49a9 16d40aa7379a805fa9ea95dca5316b6ea793ad93 M	src
```

**Comment by andrewbird** [comment]
Hi,
1/ what is the result of
 setxkbmap -query
2/ in boot.log what are the values for detected primary and secondary keymaps? You may need to run with -Da to see that, I don't remember offhand just what the print level is to see that.

Andrew

 of

**Comment by stsp** [comment]
Sorry for being a bit slow these days.
Because of this project I've got the position
of the virtualization architect in one of the
world's top IT companies (had to read the
latest Bart's KVM patches before an interview :),
so have to change the living location now.
I'll soon get to see if this regression is reproducible
(unless @andrewbird already checked that it is not,
as his comment may imply).

**Comment by andrewbird** [comment]
Hi Stas, no I didn't check anything, just asked for some logs to see, a) if the keymap selection was correct, b) so I'd know where to start to debug from.

Andrew

-------- Original message --------
From Stas Sergeev <notifications@github.com> 
Date: 07/05/2016  14:20  (GMT+00:00) 
To stsp/dosemu2 <dosemu2@noreply.github.com> 
Cc Andrew Bird <ajb@spheresystems.co.uk>,Mention <mention@noreply.github.com> 
Subject Re: [stsp/dosemu2] comma on numpad isn't recognized (#171) 
 
Sorry for being a bit slow these days.
Because of this project I've got the position
of the virtualization architect in one of the
world's top IT companies (had to read the
latest Bart's KVM patches before an interview :),
so have to change the living location now.
I'll soon get to see if this regression is reproducible
(unless @andrewbird already checked that it is not,
as his comment may imply).

**Comment by andrewbird** [comment]
Hi,
 I assume you have a German keyboard with a Comma where the Decimal Point would be on a UK one(next to the zero)? I did test here on UK keyboard and the Decimal Point on keypad doesn't print anything in the DOS (X or SDL) window on current git devel. For reference I attach my xkb info and the interesting portion of boot.log
~~~
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     gb,fr
variant:    ,
options:    shift_caps_toggle
~~~
~~~
CONF: detected layout is "uk"                                                   
CONF: detected alternate layout: fr-latin1                                      
~~~

now if I add a German layout and promote it to primary I find the keypad Comma is not working either

~~~
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     de,gb,fr
variant:    ,,
options:    shift_caps_toggle
~~~
~~~
CONF: detected layout is "de-latin1"                                            
CONF: detected alternate layout: uk                                             
~~~

Using xev I can see that the event that key generates for both DE and UK keyboards is 
~~~
keycode 91 (keysym 0xffac, KP_Separator)
~~~

There appears to be some mapping for that in src/plugin/translate/keysym_approximations.c
```
#ifdef HAVE_UNICODE_KEYB                                                        
        { KEY_PAD_SEPARATOR,    U_COMMA },                                      
#endif                                                                          
```
but as you can see it's ifdeffed. The only place I can see that defined is 
~~~
src/plugin/kbd_unicode/config/plugin_config.h:#define HAVE_UNICODE_KEYB 2
~~~

but X and SDL include "plugin_config.h" which I think will pull in their respective versions, which don't define it
src/plugin/X/config/plugin_config.h
```
#define X_SUPPORT 1
```
and
src/plugin/sdl/config/plugin_config.h
```
#define SDL_SUPPORT 1
```

So my suspicion is that commit e7d243b081ad548c0eaa4168eeb0146f44c5afe5, as @haenschen found with the bisect, is the culprit, but quite what to do about it I'm not too sure?

I also suspect I haven't groked the whole picture here, as it would seem that mapping  KEY_PAD_SEPARATOR to U_COMMA is not the final solution, as it would be incorrect for keyboards other than German. The keymap files for each appear to try to do the correct thing

./etc/keymap/de-latin1
~~~
  numpad 0=                                                                     
     "789-456+1230,"
~~~

 ./etc/keymap/uk
~~~
  numpad 0=                                                                     
     "789-456+1230."                                                            
~~~

**Comment by stsp** [comment]
Thanks for analysis, then its just the missing
includes, fixed.
For me the bug didn't happen, and the character
printed was '.' not comma. So I suppose the
approximation tables are used only when the
appropriate entry in the keymap is missing.

**Comment by andrewbird** [comment]
That looks to be fixed just fine. I get Decimal Point with UK keyboard and a Comma with DE layout on my UK keyboard. @haenschen can you confirm it's okay with real German keyboard, please?

**Comment by haenschen** [comment]
Hi!
First of all congrats on your new job @stsp! You definitely deserve it.
Secondly thanks for your effort guys, as Andrew pointed out the German decimal mark is a comma while in some other countries it is a point. However it is working just fine after the latest commit, thanks!

**Comment by stsp** [comment]
Thanks. :)
