### ISSUE TITLE
Dosdebug: how to show current value of calculated memory location

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#190]
I have a small question about how to evaluate a memory location in dosdebug. The traced line I'm interested in is

```ASM
AX=0000  BX=5ec4  CX=0000  DX=0000  SI=5516  DI=481e  SP=dd98  BP=ddc6          
DS=3088  ES=4089  FS=0000  GS=0000  FL=000a7396                                 
CS:IP=9490:0ecd       SS:SP=3088:dd98                                           
9490:0ecd 2681BDB2162B01   cmp  word es:[di+16B2],012B                          
```

What would the sequence of commands to evaluate 'es:[di+16B2]'?
It had crossed my mind that it might be nice to add a command to dosdebug to parse, discover the address and print the value, but first I need to know how to get that value, and my last messing with DOS memory references were probably 25 years ago. My dreamt up syntax might be:
~~~
print es:[di+16B2] as word
~~~

**Comment by stsp** [comment]
> What would the sequence of commands to evaluate 'es:[di+16B2]'?

(es << 4) | ((di+0x16b2)&0xffff) IIRC.
And in protected mode you'll need to so GetSegmentBaseAddress().

**Comment by stsp** [comment]
You don't need a special command for a simple things like this.
You can just extend the output, for example:

9490:0ecd 2681BDB2162B01   cmp  word es:[di+16B2],012B  # addr1=0xbeaf value1=0xbad

**Comment by andrewbird** [comment]
Thanks for the example. It would be very nice to extend the current line info to include such a thing, but doesn't that mean either that the disassembler would need extending with access to the current regs, or the tracer would need to know how to disassemble?

**Comment by stsp** [comment]
Something like 15 years ago I coded up the
instr_mem() function that calculated the address
for any instruction that does memory access. But
the use-case have disappeared and Bart didn't apply the patch.

@bartoldeman do you still have this patch?
Remember you told me you know where to get it once
it is needed. :)

**Comment by stsp** [comment]
> Remember you told me you know where to get it once
> it is needed. :)

IIRC this was told because the patch was uploaded
somewhere to SF private dirs. But I am not sure if they
are still available. And I certainly don't remember how
to access them.

**Comment by stsp** [comment]
@bartoldeman can you somehow recover the private
content we had in htdocs on SF 10 years ago?
I tried but unsuccessfully. Seems like I can't access
the project's htdocs now.

**Comment by andrewbird** [comment]
Any luck finding the old patch, it would be so useful to me?

**Comment by stsp** [comment]
Only @bartoldeman knows where the patch is.
I don't seem to have the privs to access the dosemu1
project via ssh (even though I had that priv in the past).

**Comment by stsp** [comment]
You can take a look into this project:
http://udis86.sourceforge.net/manual/libudis86.html
Looks like it provides the needed functionality, in
particular you are interested in ud_operand_t.lval.
The question whether or not do we need yet another
lib just for this, is difficult one. But if you have enough
time to work on this, then the answer is most likely
"yes". For example, it may be better to use that lib
instead of the hackery I coded in instr_dec.c; instead
of the hackish API that I export via instremu.h, and
perhaps even replace the hand-made disasm of dosdebug.
Of course we could find yet another hackish instr_mem()
patch, but why not to use the nice lib for everything if
someone have enough time to make a good integration.
OTOH since all the hackish decoders are already written,
this task has a cleanup priority so the one have to carefully
consider the amount of work it can absorb and whether
it worth a try. The extra care must be taken to make sure
it is portable to DOS: instr_dec.c is used in my DOS port
of msdos.c that I build with djgpp. If instr_dec.c is moved
to this lib and stops compiling for DOS, then that would be
a problem. Though I really suspect the disasm library is
easy to compile on anything, so the portability is probably
not a problem, just something to check.

**Comment by andrewbird** [comment]
Interesting. But I couldn't find any example of where the memory addresses were resolved from the current values of registers. Except for the jump offsets being calculated from the instruction pointer, it still looks like a static disassembler. I would expect to have to pass in the current regs on every call to ud_disassemble() for the calculated address values to end up in .lval. Or perhaps I'm expecting all the work done for me already and it needs extending?

**Comment by stsp** [comment]
You need to resolve the register values yourself
(of course, how do you suppose to pass them to this
lib, in what format?), but the lib provides you with all
the needed info:
.base refers to the base register
.index refers to the index register
.scale is the index scale
.lvalue is the immediate offset it seems
.type must be UD_OP_MEM or otherwise it is not a mem ref

Based on these values you can resolve the register values
with a simple switch statement. The lib doesn't seem to provide
any helpers to calculate SIB, but I suspect you can do something
like
mem_ref = base_reg + index_reg*scale + lvalue

**Comment by stsp** [comment]
Hmm, its even documented exactly the way I wrote above:


UD_OP_MEM

    A memory operand. The intermediate form normalizes all memory address equations to the scale-index-base form. The address equation is available in,

        base - base register as an enumerated constant of type enum ud_type. Maybe UD_NONE, in which case the memory addressing form does not include a base register.
        index - index register as an enumerated constant of type enum ud_type. Maybe UD_NONE, in which case the memory addressing form does not include an index register.
        scale - an integer value by which the index register must be scaled. Maybe 0, denoting the absence of a scale component in the address.
        offset - An integer value, which if non-zero represents the size of the displacement offset, and is one of 8, 16, 32, and 64. The value is available in lval.

**Comment by andrewbird** [comment]
It doesn't seem to be packaged for ubuntu/debian, so would you autoconf detect for it and conditionally build the debugger or import the source into the dosemu tree?

**Comment by stsp** [comment]
This lib is available in fedora (udis86-devel),
and in ubuntu's ppa. This means there is certainly
no reason to embed it into dosemu tree.

Conditional debugger looks also like a bad idea,
not only because it is nice to always have it available,
but also because this lib could power other components
too, that can't be optional (like msdos.c).
Although hard dependency on the lib that is still in ppa,
looks a bit risky.

I'd solve it the following way: we can have it in a
separate branch for testing. If we find it very cool and
indeed replace the core parts with it, then we can start
pestering ubuntu about including that. If they do, we are
safe. As I said, fedora already has it, which is very good.
If ubuntu rejects, we can add a copy to our tree, but
compile it conditionally, only if the external one is missing.

**Comment by stsp** [comment]
Hmm, in fact, this library is so surprisingly small that
perhaps it is not a problem having it always included
as a fall-back, until all distros have it for quite some time.

In fact, it seems all we need is decode.[ch] files.
So I am not even entirely sure the configure should
check and prefer the external one. But to stay polite
to its authors, we probably should prefer the external
one.

**Comment by andrewbird** [comment]
There doesn't seem to be many responses in their issue tracker lately, and 114 forks in github. In 2013 somebody wrote about packaging for ubuntu https://github.com/vmt/udis86/issues/52 but also mentioned that the current version (at the time) 1.7.2 was failing tests. I think you may need to be careful about what version you choose and it might be better to import just what's needed.

**Comment by stsp** [comment]
I tried "make tests" and all tests passes, so I guess this is fixed.
"git describe" shows 84 commits after 1.7.2.

Anyway, we first need to see how it works and what
we can get from it. Then decide whether to rip it or
use external one. Right now obviously it is easier to
use the external one for testing, so the problem didn't
yet materialize. How deeply can it be integrated, is what
needs to be discovered first:
- Can we have dosdebug optional?
- Do we need to replace dosdebug's disasm?
- Do we need to re-implement instr_dec.c?
These questions should be researched to get a better
understanding of the lib's use.
