### ISSUE TITLE
Dosdebug: bpload fails to load command

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#191]
I tried to use the bpload command within dosdebug, but the program fails to load. e.g.

start DOS/dosemu
~~~
bin/dosemu.bin -D+dRW -n -f test-imagedir/dosemu.conf --Fimagedir test-imagedir
~~~
then start dosdebug
~~~
ajb@polly:/test/dosemu2.git$ bin/dosdebug 10017

DOSEMU Debugger V0.6 connected
- type ? to get help on commands -
Reading map file nm /test/dosemu2.git/2.0-pre5/bin/dosemu.bin | grep -v '\(compiled\)\|\(\.o$\)\|\( a \)' | sort
4326 symbol(s) processed
highest address 099e5020(_end)
system state: running
AX=1100  BX=0392  CX=0001  DX=0000  SI=00ee  DI=03bc  SP=0a66  BP=0a6e
DS=0070  ES=0133  FS=0000  GS=0000  FL=00083246
CS:IP=fc00:011a       SS:SP=0133:0a66

fc00:011a F4               hlt
stop
system state: stopped
AX=0100  BX=0000  CX=00f9  DX=007f  SI=010d  DI=01fb  SP=0a90  BP=0000
DS=0133  ES=0133  FS=0000  GS=0000  FL=00033246
CS:IP=fc00:022c       SS:SP=0133:0a90

fc00:022c F4               hlt
bpload
g
~~~
then in dos window try to run a command
~~~
cd \dosemu
lredir

Memory allocation error
Cannot load COMMAND, system halted
~~~

I tried this with both PC-DOS 2000 and MS-DOS 6.22 and with other programs

dosemu.conf is minimal :-) system is 32bit running vm86 enabled kernel (ubuntu 4.4.0-23-generic)
~~~
$_lpt1 = ""
~~~

when I kill the via dosdebug, I get more output
~~~

bpload: intercepting EXEC:


bpload: replacing EXEC with LOAD:
system state: running
AX=0b1a  BX=0004  CX=0e04  DX=0805  SI=0100  DI=0100  SP=060a  BP=0081
DS=0e90  ES=f000  FS=0000  GS=0000  FL=000a7283
CS:IP=0e90:0b67       SS:SP=0e90:060a

0e90:0b67 EBFE             jmp  short 0B67 ($-2)

dosemu killed via debug terminal
~~~

**Comment by andrewbird** [comment]
There seem to be 2 problems with this:
- The debug terminal seems to be out of sync with dos window. i.e after 'g' dosdebug doesn't show the breakpoint being hit, although the DOS window shows the command failed. Then after another command in the dosdebug window the 'intercepting EXEC' message appears
- The int 21/4b fails, presumably because of the change from EXEC to LOAD

**Comment by stsp** [comment]
I suspect this bpload can be implemented
without setting any int3-style breakpoints at all,
using only TF. But this is an exercise for the reader. :)

**Comment by andrewbird** [comment]
Thanks, this now stops okay, though I'm not sure exactly where. I had been expecting that on break it would be sitting on the interrupt 21 about to execute the load. That's the behaviour we see with just plain 'bpint 21'.

**Comment by stsp** [comment]
Why would you then want bpload at all?
Just to stop on int21 with ah=4b? That would
be an entirely useless command then.

**Comment by andrewbird** [comment]
To be honest a generic 'stop on interrupt with register == ??' would be most useful, but I'm not sure if that's possible to do? In the meantime a 'bpload' that allows me to stop before the DOS program I'm running loads a TSR, would allow me to set a break point for after the load so there was no need to trace into it. So rather than the loaded program being of interest, it's a way to avoid it in the trace.

**Comment by stsp** [comment]
Everything is possible, for example in gdb you
can specify any condition to the breakpoint.
Of course it just sets an unconditional break-point
and then checks the conditions by hands, which is
quite slow but works. I'd estimate in dosdebug this
will take a couple of days on coding, so not me.
I am not saying it is useless, it would actually be very
useful, but its just not what bpload does, and making
bpload to behave that way (instead of adding a new
command for generic conditionals) would be a plain
regression.

There is an interesting trick though, that you may find
useful. If in mhpdbg.c:469 you comment out mhp_clearbp(),
then it will likely stop also on program's exit, which seems
what you are asking for. If it is what you need, I may consider
a PR with such a strange and undocumented bpload enhancement.
