### ISSUE TITLE
ERROR: mprotect to lfb?

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#204]
Running on Ubuntu 16.04 64-bit with Linux kernel 4.4.0-28. Staying on the latest commit in the devel branch (364eaed6db38299f3df582e83eb8b3c97a95101a).

Starting DOSEmu2 is OK, but when I start a graphical program (PC/GEOS) which is configured to 1024x768 resolution with 16-bit colours, I get the message "ERROR: mprotect to lfb?" printed to the console. The DOSEmu2 window resizes to the desired resolution, but the content is not drawn. I have to manually kill the "dosemu.bin" process.

I've attached the "boot.log" which contains the backtrace to the message.

With the commit 694a97db885c9789282008648f88a1498556ae04, all has been working flawless.

Need to see if I find the time to bisect this to the specific commit (maybe later this day or tomorrow).

**Comment by bolle732** [comment]
Here the "boot.log"
[boot.log.zip](https://github.com/stsp/dosemu2/files/356525/boot.log.zip)

**Comment by stsp** [comment]
Thanks for your testing.
I've actually expected something like this,
because I put the error to the code I didn't
understand. Bart, what was the reason of switching
the page protection for LFB? Anyway, I guess I can
remove the code that does this, but your log doesn't
help me to identify it:

Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Vorgang nicht zulässig.

Try
echo 0 >/proc/sys/kernel/yama/ptrace_scope

In a mean time I can enable the alternate backtracer, as people
seem to have constant problems with gdb (you at least have it
installed, others do not).

**Comment by stsp** [comment]
Now the alternative backtracer is enabled, so,
in case you built dosemu with libbfd, we can have
a good log again.

**Comment by bolle732** [comment]
I've set "ptrace_scope" to 0 and here is its "boot.log":
[boot.log.zip](https://github.com/stsp/dosemu2/files/356964/boot.log.zip)

Regarding the alternative backtracer, have to try it later.

**Comment by bolle732** [comment]
Now with installed "liblfb-dev":
[boot-gdb-lfb.log.zip](https://github.com/stsp/dosemu2/files/356983/boot-gdb-lfb.log.zip)

**Comment by stsp** [comment]
You need to use
./default-configure -d
for debug builds.
I'll try to get some info from this log too,
but it is still bad.

**Comment by bartoldeman** [comment]
@stsp what do you mean with "switching the page protection"? This commit? 24fd22f18d29e1a4e8d48a80b06fae9cdf6dc402

Obviously we need page protection for LFB to track dirty pages, unless I am missing something here.

**Comment by stsp** [comment]
Yes, I have for a moment forgot that we are
still not on KVM here. :) Would it make sense to
stop doing so, and use memcmp() instead?
We already have the separate thread that could
do this.

Anyway, I'll now restore the mprotect functionality.

**Comment by stsp** [comment]
Should now be fixed.
Coding late at night doesn't produce the
good results obviously. :)
Thanks for everyone involved.
I should probably try the memcmp() approach though,
as IMHO mprotecting lfb is a sub-optimal technique.

**Comment by bolle732** [comment]
Ok, thanks for the hint regarding the debug switch for "default-configure". With the latest commits it works again.

**Comment by stsp** [comment]
@bolle732 You can try non-modeset console mode.
It would be good to get that tested sometime (I do not),
plus you'll get the fastest possible LFB there.

**Comment by stsp** [comment]
For simple (non-planar) modes and for lfb
we can do memcmp() to detect dirty pages.
If done carefully, this can be much faster
than taking a page fault.
The optimizations that come to the mind:
- use separate thread for memcmp
- use per-page locks so that it can run in
parallel with the render thread
- use VM tricks to create back-up pages,
rather than malloc/memcpy.

I think this will speed up vgaemu a lot.
BUTT... It looks as if it is not needed for
cpu-emu, and for kvm we are already very
close to running without page protection.
So is this only good for DPMI apps?
I wonder if then it is worth a trouble.
@bolle732 does your prog use DPMI?

**Comment by bolle732** [comment]
@stsp Regarding "non-modeset console mode", do you mean disabling modeset of the Linux kernel (by Grub) ? I'm just curious, never tried that with X and Unity on Ubuntu. But will do if I get some hints as my replacement notebook is waiting for setup...

All PC/GEOS versions don't use any DOS extender / DPMI. I have "$_dpmi" set to (0) in the "dosemu.conf".

**Comment by stsp** [comment]
Yes, in grub you add "nomodeset=1" to kernel
command line. Then the only X driver available
will be "vesa" and 3D will be slow. You don't need
to run X at all then. Log in to the text console and
run
dosemu -s

**Comment by bolle732** [comment]
Ok, thanks for the advice.

Would be a nice test for reference regarding possible speed... Will see when I get the time for it.

**Comment by stsp** [comment]
In fact, lfb was still completely broken.
I've fixed it again now.
Please re-test.

**Comment by bolle732** [comment]
Ok, on Monday I'll have access to the 64-bit machine.

**Comment by bolle732** [comment]
I've tested the latest commit d9f66d30ad1160bbbb3c12984fce27a2226d3aa7 of devel and it works fine there. Thank you!
