### ISSUE TITLE
Running an unrecognised command locks up DOSEMU

### ISSUE THREAD

**Issue by fstirlitz** [stsp/dosemu2#221]
Steps to reproduce:

1. Create a symlink to `generic.com` with a name that DOSEMU doesn't recognise (say, `xyzzy`).
2. Run it inside DOSEMU; it locks up.

It's a quite funny bug, actually. When `commands_plugin_inte6` detects `generic.com` has been called with an unrecognised name, it calls `com_error`. Which looks like this:
```c
int com_error(char *format, ...)
{
	int ret;
	va_list args;
	va_start(args, format);
	ret = com_vprintf(format, args);
	verror(format, args);
	va_end(args);
	return ret;
}
```
It uses the same `va_list` twice which I guess is what generates a segmentation fault in when `verror` calls `vfprintf`. This is caught by DOSEMU's custom SIGSEGV handler, which detects that and tries to report it again through `verror`. Which is what causes the lockup, because `verror` holds a mutex while calling `vfprintf`.

Bug found because I still had a `uchdir` symlink installed. I don't know why support for `uchdir` was removed in the first place anyway. It doesn't seem to accomplish anything apart from breaking compatibility.

Several issues here, and I'm not so sure what's the best way to handle all of them. Ideally, DOSEMU with a KVM core wouldn't need to have a custom SIGSEGV handler at all.

**Comment by stsp** [comment]
Thanks!
So if you analyzed the problem in such a great
details, why not to do a pull request? I've done what
you say.

> removed in the first place anyway. It doesn't seem to accomplish anything apart from breaking
> compatibility.

I am not sure why people take the compatibility with
something (with dosemu-1?) for granted: there is no
compatibility with dosbox either. Of course I tried to
add the compatibility stubs for the most common dosemu-1
tools (like lredir) just so that people could use dosemu-2
as a drop-in replacement in most cases, but uchdir/ugetcwd
is not among those frequently used things and is not used
in a default setup. So while lredir says "this is deprecated",
I wonder if adding such stubs and deprecation periods for
things like ugetcwd is even worth the trouble.

Actually, I admit that because I parasite on ~/.dosemu dir,
people expect the compatibility. This question was iterated
many times already, but there is no definite decision.
For example, I'd be fine with switching over to use ~/.dosemu2.
The upside of this is that dosemu2's installer uses many new
features unrecognized by dosemu1. So it would be very good
to have things re-installed the new way.
But there are also the binary names and the config dir - these
I'd like to preserve and support the dosemu1 config fully. Yet
if we move to ~/.dosemu2, there is a question why to keep sharing
config then, etc. Users have voted both ways to this. Some
want the new features right away, and others are stuck to
dosemu1 tools and configs, and want to run dosemu2 only
in parallel to dosemu1. Knowing how much users are stuck
to dosemu1 would be helpful at making the decision. If there
is enough of demand to run them in parallel, I'll do.

> Ideally, DOSEMU with a KVM core wouldn't need to have a custom SIGSEGV handler at all.

There is no urgent need to run DPMI inside KVM right now.

**Comment by fstirlitz** [comment]
> So if you analyzed the problem in such a great details, why not to do a pull request? I've done what you say.

The primary reason I wrote this report is to highlight this more general issue of stability being compromised by custom signal-handling shenanigans. There may be other bugs like this lurking in the code, and I think they might be easier to diagnose if dosemu could just dump core like any other program.

(And I didn't actually post a solution. For the immediate problem, I'd use two `va_list` variables and `va_copy`. But never mind that.)

> I am not sure why people take the compatibility with something (with dosemu-1?) for granted: there is no compatibility with dosbox either.

I find it ironic when the developer of a package whose entire _raison d'être_ is making it possible to run binaries compiled for an operating system from the 1980s says people shouldn't care so much about compatibility. _Of course_ users are going to expect compatibility. It's easily one of the most desirable qualities in _any_ software. One of the surest ways to anger your users is to make incompatible changes without a good reason. Need I mention [You-Know-Who](http://0pointer.de/blog/), whose software keeps igniting flamewars to this day? (Even though he _did_ often have good reasons for breaking compatibility, or at least better ones than... I don't know, aesthetics? You haven't actually explained why you did this.)

> There is no urgent need to run DPMI inside KVM right now.

Like I said, I'd expect this setup to be more stable. And tighter integration with KVM may open the door to some other desirable features (Ring-0 support in PM? VCPI?), which I'm not sure how feasible are now. It's just a suggestion, though.

**Comment by stsp** [comment]
> compromised by custom signal-handling shenanigans. There may be other bugs like this lurking in
> the code, and I think they might be easier to diagnose if dosemu could just dump core like any
> other program.

The current behaviour is to dump the backtrace to the log.
This is usually better than the coredump, since the coredump
on user side is not very helpful. Unfortunately you've found
the case where this doesn't work.

> compatibility. Of course users are going to expect compatibility. It's easily one of the most
> desirable qualities in any software.

With what? Do you want a compatibility with dosbox maybe?

> Like I said, I'd expect this setup to be more stable.

We may have DPMI/KVM one day, but it will still be optional.
