### ISSUE TITLE
Settlers2: Sounds play with echo when using SDL

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [stsp/dosemu2#24]
sounds as if  they were played twice ore more

**Comment by stsp** [comment]
Try deleting libao.so and see if that helps.
Maybe somehow they work together?

**Comment by stsp** [comment]
I suspect you were renaming libao.so
instead of deleting it. And now you returned
it back, without re-building and re-installing.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
With or without libao makes no difference, both have echo.
But dosemu claims about missing libao when it is not available, even though -S is given.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
I tell you what the reason is.
The throttled cpu power.
I can switch the 'echo' on and off by switching the power from powersave to ondemand/performance.

**Comment by stsp** [comment]
> But dosemu complains about missing libao when it is not available, even though -S is given.

That's normal: libao can be used also for wav writing,
so dosemu is trying to load it anyway. But I'll see about
changing the plugin logic so that it never try to load the
missing plugins...

> I can switch the 'echo' on and off by switching the power from powersave to ondemand/performance.

Doesn't tell me anything.
I guess this is a pulseaudio bug.
If both SDL and libao has that (i.e. both -S and without),
then try to kill pulseaudio (rename its binary first, or it
will be restarted) and try again. Without pulseaudio the
problem will likely not happen.
You can also try SDL_AUDIODRIVER=alsa but I am
afraid pulseaudio will intercept even that, so better to
rename it and kill it, then try.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
=== configuring in libao
./configure: line 1666: syntax error near unexpected token `,,'
./configure: line 1666: `XIPH_PATH_AO(,,'
Configuration for libao failed, disabling
