### ISSUE TITLE
boot.log crash in Foxpro 2.6 DOS

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#243]
Works well most of the time. Sometimes I hit a key in one of the editors and DOSEMU crashes.

4.7.6-1-ARCH x86_64
dosemu2-git 2.0pre6.1+dev+26+g22cf221-1

I tried to enable debug but the compile stopped.

```
Updating version.h
In file included from backtrace-symbols.c:53:0:
/usr/include/bfd.h:35:2: error: #error config.h must be included before this header
 #error config.h must be included before this header
  ^~~~~
```

[boot.log.zip](https://github.com/stsp/dosemu2/files/517102/boot.log.zip)
[boot.log.zip](https://github.com/stsp/dosemu2/files/517178/boot.log.zip)

**Comment by stsp** [comment]
Please do the following things:
1. Report the build failure to archlinux bugzilla.
The "#error config.h must be included before this header"
is a holly crap, and the /usr/include/bfd.h I have in fedora
doesn't even contain this string.
2. Comply to what the console messages tell you, namely:
sh: gdb: command not found
backtrace failure
ERROR: Please install gdb!

**Comment by stsp** [comment]
Ah, ok, your second log indicates you did part 2
(there was no need to upload the initial log).
Unfortunately it still doesn't log anything.
You should try:
su -c "echo 0 >/proc/sys/kernel/yama/ptrace_scope"

**Comment by stsp** [comment]
Also you should configure dosemu with debug info:
make clean
./default-configure -d
make -j 9

**Comment by stsp** [comment]
Ah, which you can't do because of the build
failure. :) Nice.
Can you hack /usr/include/bfd.h and just remove
the #error from there?

**Comment by stsp** [comment]
I added the --disable-xbacktrace option.
Now you can do:
./default-configure -d --disable-xbacktrace
to avoid the libbfd failure and still get the debug build.

**Comment by severach** [comment]
https://aur.archlinux.org/packages/dosemu2-git/

The Arch bugzilla only applies to Arch repo packages. There is no Arch package yet. All that exists is an AUR git package and I own it. With your help I'll get it wrangled into shape so it's easy to use. For example my new debug option forces gdb to be installed to eliminate that source of support issues. It's a lot easier to set one option and have all the right things happen rather than try to coax each user through step by step.

I have debug enabled and building. Unfortunately debug disables freedos integration so the build is of no use.

```
WARNING
No FreeDOS tarball (dosemu-freedos-1.0-bin.tgz) found. If you are not
% grep tarball compiletime-settings 
  fdtarball dosemu-freedos-1.1-bin.tgz
```

If you want an Arch machine for build testing you can install Manjaro in less than 1 hour or I can provide you with a sudo login into a secure Arch machine.

**Comment by stsp** [comment]
> The Arch bugzilla only applies to Arch repo packages. There is no Arch package yet.

/usr/include/bfd.h is not from dosemu2, and as
such, it can be the subject for bug report.

> example my new debug option forces gdb to be installed to eliminate that source of support issues.

But if you fix libbfd, you don't really need to force
the gdb installation, because the backtrace produced
by gdb is only slightly better than the one of libbfd.

fdtarball dosemu-freedos-1.1-bin.tgz is defined similarly
in both compiletime-settings and compiletime-settings.devel,
so I really don't know why with -d it doesn't find the fd tarball.
Cound you double-check that you are doing things right, and
that only this -d causes the fd tarball problem?

I'll google for Manjaro, thanks for the hint.

**Comment by stsp** [comment]
Ah, its just a distro...
Well I may need the ssh login (not sure why
you wrote "sudo login", probably a typo) for
debugging the crash itself. But for the build
issues let me hope you'll be able to sort them
out yourself before I do. :)

**Comment by stsp** [comment]
And even though the gdb backtrace is slightly
better, it is usually disabled and you need to
do this "echo 0" stuff to enable it via procfs.
That's why I give up on forcing people to install
gdb. It might be better if you fill the bug report
to fix libbfd.

**Comment by severach** [comment]
>/usr/include/bfd.h

I fixed that bug by following the instruction. I added `#include "config.h"` to the beginning of `backtrace-symbols.c`. No evidence yet that Arch Linux binutils::bfd.h has any problems.

>fdtarball dosemu-freedos-1.1-bin.tgz

I didn't know that `default-configure -d` switches to compiletime-settings.devel. Pushing the settings into .devel fixes the problem.

>su -c "echo 0 >/proc/sys/kernel/yama/ptrace_scope"

That can be patched into the dosemu launcher for the Debug build. A PKGBUILD done right just works. No fussing with the users.

>you wrote "sudo login", probably a typo

Build your own Manjaro and you'll have sudo access. You can also have sudo access on my build server. Sudo is necessary for testing the package.

I have debug building properly so I should be able to produce some debug output on the next crash.

**Comment by stsp** [comment]
> No evidence yet that Arch Linux binutils::bfd.h has any problems.

It appears to be a common problem:
https://sourceware.org/bugzilla/show_bug.cgi?id=14243
I find it absolutely silly for the common headers of
/usr/include to require some config.h that may not
even exist at all. And, according to the comments,
the problem is in this check:
#if !defined PACKAGE && !defined PACKAGE_VERSION
which, of course, makes no sense (they also suggest
to #define PACKAGE "foo" as a work-around - great).
Further, as I said, fedora and ubuntu (at least, those
that I've tested) have no such problem.
So I really suggest to deal with it on libbfd level. But
I can also apply the work-around to make other's life
easier. So feel free to open a PR.

> That can be patched into the dosemu launcher for the Debug build.

Not sure what launcher you mean because I am not familiar
with arch. But please note that this "echo" stuff requires
root. If the launcher you refer to is arch-specific and
does always have root, then its your decision to use it.
But having the libbfd's backtrace is a good compromise
that does not require root.

> Build your own Manjaro and you'll have sudo access.

I can't speak for arch people but I think your wording
is bad. There can be an ssh access to PC. "sudo access"
to what, to PC? Or to root privs? :) Bad terminology
(unless arch people use their own, of course)

> I have debug building properly so I should be able to produce some debug
> output on the next crash.

That would be good, thanks.

**Comment by andrewbird** [comment]
I see in Ubuntu's patchset to binutils 2.26 the check is being removed from the header, see https://launchpadlibrarian.net/277619239/binutils_2.26.1-1ubuntu1~16.04.3.diff.gz search for 'PR 14072'. So at least one distro thinks forcing autoconf usage/or fudging PACKAGE variables for bfd.h inclusion is wrong. I couldn't find a corresponding bug in Ubuntu's Launchpad bugtracker, so I suppose it was fixed by the packager initially.

**Comment by stsp** [comment]
> So at least one distro thinks forcing autoconf usage

Fedora too, and I hope many other as well.
I don't see the point, really. If they wanted some
real system-specific info (as opposed to just defining
PACKAGE), they could include the glibc-provided
configuration headers of /usr/include/bits.
Of course we can add the work-around. And as silly
the problem is, the sillier work-around we can add.
I'd rather add "#define PACKAGE "foo"" instead of
including config.h, to emphasize our disagreement.

**Comment by stsp** [comment]
I looked at how other projects handle this, and
applied the fix.

**Comment by severach** [comment]
I used DOSEMU heavily for a month and no more crashes. I guess I'll close this.

**Comment by stsp** [comment]
OK, thanks for the follow-up.
Since I don't think the problem is fixed, but backtrace
should now work properly, feel free to upload the log later.

A few hints how to reproduce the problem:
you need to start "dosemu -X" to get Xorg plugin used
instead of SDL.
The crash seems to be related to mouse presses, rather
than the key presses (maybe you need to press kbd and
mouse together).

**Comment by severach** [comment]
Now that you mention it, the crashes happened on a day when all I had was the touch pad. Touch pads are always being hit by accident. Over the last month I always disable the touch pad and use a real mouse.
