### ISSUE TITLE
fdisk and mkfatimage16

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#244]
linux fdisk seems to be able to work with
image files. But it doesn't pick the ones produced
by mkfatimage16, at least not automatically.
Passing geometry by hands didn't work for me.

@andrewbird Have you ever tried this?

**Comment by andrewbird** [comment]
Had you accounted for the 128 byte dosemu header, somehow?

**Comment by stsp** [comment]
Thanks, this was indeed the problem.
Should we add some option to skip it maybe?
I wonder how much it is really needed...

**Comment by andrewbird** [comment]
I had wondered if we could reuse qemu images and hence its tools, but how would we inform Dosemu of the disk geometry? I wonder how qemu deals with this?

**Comment by stsp** [comment]
Is there some info that is needed and is not
in ptbl? IMHO it would be nice to first support
the raw images (that fdisk can also use) first,
then think about qemu. I personally don't think
we can share much with qemu image, as people
rarely use DOS under qemu.

**Comment by stsp** [comment]
Andrew, please note that we already support
directories as an images! They do not even have
ptbl. So I am pretty sure there is nothing important
in the header. Or is it?

**Comment by andrewbird** [comment]
I guess the lack of geometry specification outside the partition table is a problem when we would like DOS to partition and format a bare image. This is a common operation I do when trying to get old DOS versions to boot so I can create an image with same geometry as fatfs does for log comparison etc. I suspect that Dosemu could be enhanced to understand the :type1/2/9 suffix for image files and that would suffice for my use.

Regarding the qemu etc, I was thinking that reuse of their image format might allow us to kill our tools rather than actually share info between Dosemu and DOS/Qemu instances. It seems that the Qemu raw format has no special header anyway, so it's just a zeroed file. In any case our mkfatimage16 does creation of the image, 1 partition, fatfs filesystem, and population of the filesystem in one invocation, so I don't think anything qemu has would be as good. Using fdisk then mkfs.fat has little benefit as mkfs.fat needs to work at the partition level and so would require root access by something like kpartx.

Mtools might work easier without the complication of having to offset 128 bytes for the Dosemu header.

**Comment by stsp** [comment]
> I guess the lack of geometry specification outside the partition table is a problem
> when we would like DOS to partition and format a bare image.

Isn't it possible to induce the geometry based on the image size?

**Comment by andrewbird** [comment]
I don't believe so. Wouldn't that be like the floppy disk image geometry detection that we recently decided was a bad idea? in fact I think it would be worse, because at least with the floppies there are a known set of geometries. If you really want to kill off the header, do it, but I guess Dosemu will have to either support existing images, or arrange to modify them. I can add the type1/2/9 thing later when it becomes a problem to me. I suspect that in the general case it would be easier for the user without the header, and only a small inconvenience to myself.

**Comment by bolle732** [comment]
I believe, that the (Sea)BIOS used in QEMU needs to do the geometry 
stuff. If this could be adapted by DOSEmu, it would be nice. Then one 
can use the standard Unix tools and for example, fdisk should work out 
of the box.

The only concern I have are the current users with their already 
existing image files.

Only my 2 cents...

**Comment by andrewbird** [comment]
I just had a thought, what about using xattr to store the geometry on a headerless image?

**Comment by stsp** [comment]
> I don't believe so. Wouldn't that be like the floppy disk image geometry
> detection that we recently decided was a bad idea?

The problem I had with floppies is that we compared
the size against the fixed set of sizes. That troubles the
image creation for the user. And just "calculate" the floppy
geometry based on the image size is silly too, as there is
only a fixed set of floppy geometries.
Of course we can support the fixed set of HD geometries
too, but automatically calculating it may also be supported
I think. Something simply unneeded for floppy. For floppy
we can simply expand the image to the known size, but hdimage
can't be treated that way if it is already larger than the pre-defined
types for example.

> I just had a thought, what about using xattr to store the geometry on a headerless image?

But do we really need it? IMHO we can have a set of hdimage
types and the way to induce the geometry if the type is not set.
We can also have the way to manually specify the geometry in
config - then the image will be treated with that geometry, and
its size will be adjusted perhaps. But if nothing is specified, we
calculate.
Do you see any problems with this?

**Comment by stsp** [comment]
Hmm, maybe we indeed can employ the
floppy technique? We can use maximum possible
CHS values and enlarge an image when needed.

**Comment by andrewbird** [comment]
Sorry for the late reply. I don't see any problems with anything you mention. My only thought is that it's developing into quiet a project just to get rid of the header. Correct me if I'm wrong, but aren't hdimage files always just a single partition, since they are one image per Dosemu file? Fdisk compatibility would seem to be of limited use in such a situation.

**Comment by stsp** [comment]
Maybe.
What other tools do we have to create an
fdisk-compatible hdimages?

**Comment by stsp** [comment]
... with creating some FS on the partitions,
without manually specifying offsets to mkfs.

**Comment by andrewbird** [comment]
AFAIK even if you have an fdisk-compatible image file with a partition table you'll need to specify offsets somehow to mkfs to index to the correct partition. To me that means kpartx, AKA kernel loopback and that means root privs. Or is there some other way to select the partition within the image file to be formatted with mkfs?

I think I'm just not getting it, as I don't see the great advantage in having fdisk-compatible hdimages. But don't let me stop you, I'm sure it'll become clear to me later.

**Comment by stsp** [comment]
Does kpartx work with image files, or only with real
devices?
Yes, it requires root, so even if it works with image
files, someone may prefer using something else.

The advantage for dosemu is to support the raw
hdimages. I agree with you it is not a big advantage
because no one uses hdimages with dosemu anyway.
But there can be an advantage for mkfatimage16
itself by making it useful outside of dosemu.

**Comment by andrewbird** [comment]
Here's an example https://nfolamp.wordpress.com/2010/08/16/mounting-raw-image-files-and-kpartx/




-------- Original message --------
From Stas Sergeev <notifications@github.com> 
Date: 14/10/2016  11:56  (GMT+00:00) 
To stsp/dosemu2 <dosemu2@noreply.github.com> 
Cc Andrew Bird <ajb@spheresystems.co.uk>,Mention <mention@noreply.github.com> 
Subject Re: [stsp/dosemu2] fdisk and mkfatimage16 (#244) 
 
Does kpartx work with image files, or only with real
devices?
Yes, it requires root, so even if it works with image
files, someone may prefer using something else.

The advantage for dosemu is to support the raw
hdimages. I agree with you it is not a big advantage
because no one uses hdimages with dosemu anyway.
But there can be an advantage for mkfatimage16
itself by making it useful outside of dosemu.

**Comment by stsp** [comment]
OK, so the only advantage of using mkfatimage16
is to not require root to create the fully functional image
then.

**Comment by andrewbird** [comment]
It also populates the filesystem.

-------- Original message --------
From Stas Sergeev <notifications@github.com> 
Date: 14/10/2016  16:42  (GMT+00:00) 
To stsp/dosemu2 <dosemu2@noreply.github.com> 
Cc Andrew Bird <ajb@spheresystems.co.uk>,Mention <mention@noreply.github.com> 
Subject Re: [stsp/dosemu2] fdisk and mkfatimage16 (#244) 
 
OK, so the only advantage of using mkfatimage16
is to not require root to create the fully functional image
then.

**Comment by stsp** [comment]
I implemented this in a separate branch.
Comments & testing welcome.

**Comment by andrewbird** [comment]
Lots of stuff to look at here, I'll need to look in more detail later and test. One thing though does the auto detection of images work without header? I wonder if there is any difference between headerless image and a raw device with partitions? If so is the distinction even necessary?

**Comment by stsp** [comment]
> Lots of stuff to look at here, I'll need to look in more detail later and test.

No rush. Please take all the time needed.

> One thing though does the auto detection of images work without header?

Like this:
https://github.com/stsp/dosemu2/commit/f46229875aed632d3d862e03c4c7706b9dd871d7#diff-5acc6fceda01e7cd17adf97bc157db59R377

> I wonder if there is any difference between headerless image and a raw device with partitions?
> If so is the distinction even necessary?

From raw device you can get the geometry with
ioctls. Image can better be compared with "dir".
In fact, I simply took the geometry values from
dir_auto().
