### ISSUE TITLE
Need For Speed SE fails to start

### ISSUE THREAD

**Issue by neuromancer** [stsp/dosemu2#26]
Despite the demo of the original Need for Speed is working correctly, the special edition (with a few nice additions like 640x480 support) fails to start in the last version of dosemu2. After executing installd.exe, it corrupts the screen and i can't see the returned error. Fortunately, there is a message error in the boot.log:

    ERROR: DPMI: Warning: trying to leave DPMI when in_dpmi_pm_stack=1

An [iso](https://ia601003.us.archive.org/16/items/Need_for_Speed_The_-_Special_Edition_1996_Electronic_Arts/Need%20for%20Speed,%20The%20-%20Special%20Edition%20(1996)(Electronic%20Arts).iso) of the game is available in archive.org to reproduce this issue.

**Comment by stsp** [comment]
Gets page fault shortly after mapping lfb.
According to google it doesn't run even under
win98, so there is likely a bug in the game
itself...

**Comment by stsp** [comment]
By the way, not only NFS-demo works: normal
NFS works too. Only SE crashes.

**Comment by neuromancer** [comment]
Uhm, yes, i see. Despite of that, it is running under dosbox..

**Comment by stsp** [comment]
dosbox is very different: it allows the ring-0
usage, and so the DOS extenders can install
their own DPMI providers. This is much like
working on a bare-metal DOS or qemu.
Under windows or dosemu, the DOS extender
works in ring-3 mode, using the host's DPMI
provider, which works right in 99% of cases or
exposes some hidden bugs otherwise.
I'll try to find why exactly it crashes though.
I've done a few fixes yesterday and it seems
it now passes the point of crash when I set
cpuemu to fullsim mode, so there is still a chance...

**Comment by neuromancer** [comment]
Maybe [this](http://www.os2museum.com/wp/need-for-speed-se-video-glitch/) is related?

**Comment by stsp** [comment]
installd.exe crashes, so it is certainly not in
the game yet. Maybe if we pass the initial crash,
this fix will help as well.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by neuromancer** [comment]
Wow!. It's working (now i can finally play in 640x480 at full speed in my netbook!)
I have more games that are failing in dosemu2 and some (little) free time to test and report bugs. How you prefer to have issues reported?

**Comment by stsp** [comment]
> Wow!. It's working (now i can finally play in 640x480 at full speed in my netbook!)

This is especially good to know because I intend to
make dosemu2 a fastest emulator in the world. :)
(which dosemu-1 is certainly not)
How does your NFS-SE testing under dosemu2 compare
to other emulators, if you ever tested them too?

> How you prefer to have issues reported?

With links to the game and preferrably with an info
whether or not it works on dosemu-1. All regressions
from dosemu-1 should be fixed.

**Comment by stsp** [comment]
Oh and if you run "dosemu -S" you'll also
get a GPU accel. Then you can enable video
filtering ($_X_bilin_filt) without a performance
penalty.

**Comment by stsp** [comment]
Lets document the problem so that google
can reveal the solution to other people fighting
with that.

There is some bug in nfs-se installer, and at
one point it does
memset(0xb0000, 0, 4000);
This is an MDA text area, but no one uses MDA,
so this region may simply be unmapped and you
get a page fault. According to this article:
https://support.microsoft.com/en-us/kb/77083
it is not uncommon to have UMB at that address,
so memsetting it will corrupt UMB and crash windows
as a result. Though it may be possible to prevent
windows from using UMB by setting
LocalLoadHigh=0 in SYSTEM.INI:
http://www.old-games.ru/forum/showthread.php?t=38737
Then windows will likely not crash and NFS could work.

To fix the problem, infsd.exe can be patched: at
offset 0x02873E byte 07Ch should be replaced
with 0EBh. This will disable the offending memset().

dosemu already had a work-around to ignore such
memset(), but hack was broken and resulted in an
unrelated page fault elsewhere, which made it very
difficult to find the root of the problem. Now it works,
but it is not impossible that one day I'll put UMB at
that area, which will break the unpatched NFS-SE
again.

**Comment by neuromancer** [comment]
>  How does your NFS-SE testing under dosemu2 compare
to other emulators, if you ever tested them too?

All i can say is dosemu2 works way faster than dosbox, and its has at least a few bug fixed compared to dosemu (no regressions so far)

> With links to the game and preferrably with an info
whether or not it works on dosemu-1.

I tested Screamer 2 (not starting, it hangs even in low resolution mode) and Test Drive: Off-Road (it crashs but i can't see the error message, because the screens gets corrupted)

Do you want both reports with link to the games (i'm using emuparadise.me and archive.org)? 

> Oh and if you run "dosemu -S" you'll also
get a GPU accel.

Great. I was already using -S. In fact, i'm not sure how you can get the sound working in a modern linux distro without using SDL. Don't you think it is better to have -S by default?

**Comment by stsp** [comment]
Screamer has old dos4gw version within.
You need to replace dos4gw.exe with 1.97
version, or use dos32a like this:
dos32a.exe starth.exe
I probably need to document all these tweaks
needed to run different games.

I downloaded Test Drive Offroad and it works
perfectly for me. Except that the graphics is
somehow shakey...

> Great. I was already using -S. In fact, i'm not sure how you can get the sound working in a modern > linux distro without using SDL. Don't you think it is better to have -S by default?

Maybe one day it should. For now SDL2 is too
buggy. At least the following will need to be fixed:
https://bugzilla.libsdl.org/show_bug.cgi?id=2736
https://bugzilla.libsdl.org/show_bug.cgi?id=2893
https://bugzilla.libsdl.org/show_bug.cgi?id=2895
Also the SDL2 plugin currently peeks into an X
plugin a lot. For example, the font rendering is
not implemented (using rendering of X plugin),
same with i18n (queries XKB). So I don't see SDL2
plugin being a default any soon, unless someone
volunteers to do a lot of work on it.

Now, why don't you have sound without SDL?
Are you building dosemu without libao support?
You can fill a separate ticket about that.

**Comment by stsp** [comment]
Screamer should now work reliably with any dos4gw.
The amount of work required for that, was too much for
a single game though.
