### ISSUE TITLE
Soft links and contents of ~/.dosemu being overwritten

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#289]
I have soft links to my custom drive letters and these are being reset on every launch. When I put a soft link in place of c_drive my custom autoexec.bat and fdconfig.sys are overwritten. command.com and kernel.sys are overwritten with invalid links.

dosemu should only mess with these files on first launch. This behavior appeared out of nowhere. How do I get this to stop?
[Arch Package](https://aur.archlinux.org/packages/dosemu2-git/)

**Comment by stsp** [comment]
Please attach the -D9+d log.

**Comment by severach** [comment]
````
% cd ~/.dosemu/drives
% ln -sf ../../c
% dosemu -D9+d -X
ao_alsa ERROR: Unable to open ALSA device 'default' for playback => Invalid argument
ao_alsa ERROR: Unable to open ALSA device 'default' for playback => Invalid argument
ERROR: you appear to have unpatched vde
ERROR: Unable to boot, reinstalling...
````
Looks like you tightened up some requirements. My c didn't have links to command.com or kernel.sys. These must have had a soft handler before which disappeared. I added these links and now my c drive works without getting replaced.

**Comment by stsp** [comment]
I, yes, indeed.
I hoped no one will notice. :)
I find it very annoying that it overwrites your
config.sys/autoexec.bat without a confirmation,
but it is probably not easy to fix, because if you
had the dosemu-unbootable dir, then you very
likely also have the dosemu-incompatible startup
files. In the future we will probably implement
the installation model without copying these files
at all. So you may keep this ticket open as a
reminder if you also find the overwriting behaviour
annoying.

**Comment by stsp** [comment]
This behavior will no longer happen.
