### ISSUE TITLE
NDN problems with redirector

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#360]
In NDN, F3 doesn't open a file view window.
Also the mouse is invisible until the first click.

**Comment by stsp** [comment]
This is a redirector bug.
NDN does findfirst("file_name\*.*") and dosemu
returns an error because it is not a directory.
But I think "*.*" can evaluate to an empty string,
and then the trailing slash can just be ignored?

**Comment by andrewbird** [comment]
Probably we should check what DOS does on plain local FAT beforehand.

**Comment by andrewbird** [comment]
So a couple of observations
- problem doesn't occur on a fatfs drive, which points to the redirector
- problem still occurs with LFN disabled, which points to the redirector
- log indicats that find first for filename.ext is successful before looking for filename.ext/, which suggests that the client does not accept the result from the first as valid.

I'll write a standalone findfirst test and check the returned data

**Comment by stsp** [comment]
Thanks for taking a look!

**Comment by andrewbird** [comment]
I don't think it's a findfirst bug, I see reads and seeks on the file I'm trying to view. The seeks are a little odd, the position is at the end of the file then the redirector is asked several time to seek 0 bytes from the end, which seems a little pointless.
~~~
MFS: Entering dos_fs_redirect, FN=21                                            
MFS: selecting drive fn=21 sda_cds=0xb22b4690                                   
MFS: selected drive 2: /clients/common/dosemu2.git/test-imagedir/dXXXXs/c/      
MFS: Seek From EOF CX=0 DX=0                                                    
MFS: Seek From EOF offset=0                                                     
MFS: Seek From EOF fd=1d ofs=0                                                  
MFS: Seek returns fs=29 ofs=468                                                 
MFS: Finished dos_fs_redirect                                                   
~~~

**Comment by stsp** [comment]
I think it would be good to see what DOS
call is doing so. In case of a freedos, we
can also double-check things in the sources.

**Comment by stsp** [comment]
> seek 0 bytes from the end, which seems a little pointless.

At least on posix systems this is used
to determine the file size.

**Comment by andrewbird** [comment]
Here's a log from shortly before F3 view opens the file(ftp.ini). BTW is the logging synchronous, only I wonder if some of the 'int' logs are interleaved with the MFS somehow?
[test.zip](https://github.com/stsp/dosemu2/files/1591474/test.zip)

**Comment by stsp** [comment]
So it does a lot of seek/read sequences,
and closes the file. Then it does findfirst
`file/*.*` and that fails.
Note that not all seeks are passed to the
redirector. DOS updates the file position
internally unless it goes outside of the file,
it seems. This is why in the log you don't
see all the MFS seeks you expected, but
there should be no re-ordering.

**Comment by andrewbird** [comment]
Oh and BTW the findfirst on `filename.ext/*.*` should fail as that's what MS-DOS 6.22 did on FAT when I tested.
Yes I noticed that only seeks based on the end of the file had a corresponding function in the redirector.
I guess I should make sure that all reads adjust the position from DOS before reading, though I can't believe this is broken.

**Comment by andrewbird** [comment]
Firstly, internet access is broken at home after high winds brought down a tree, so it could be some time before I'm back on this properly. That said I've looked at logs with ndn on fatfs and mfs and they both appear to be doing similar things with regards to seeks and reads. The only suspicious thing is that ndn is doing DTA switching before findfirst, I'm not sure if we can cope with multiple interleaved findfirst/next, but it's just a feeling I have no evidence.

**Comment by stsp** [comment]
What exactly call do you mean?

**Comment by stsp** [comment]
Happy new year. :)

**Comment by andrewbird** [comment]
Ndn saves current address of DTA
Ndn sets DTA
Ndn does find first (state held in DTA)
Ndn restores DTA

Ndn may do another of the above with different DTA before find next to match the first find first. I'm not sure if the hlist stack works okay with multiple find first/next in progress from the same PSP.

Happy new year to you too!

**Comment by stsp** [comment]
Unfortunately I am a bit off from this hlist logic.
So mfs.c seems to be using per-psp findfirst
stack lists, from which it pops only when findnext
returns no more entries.
Lets start from naive questions: is this the
right thing to do at all? Does DOS really allow
stacked findfirsts, and is "no more files" a valid
terminator sign?
I think the only valid way of doing stacked
findfirst, is by manipulating DTA, as you described
above. So from the first glance, I simply don't
understand the idea behind these hlists: why
not to use DTA instead?

**Comment by andrewbird** [comment]
I was hoping you'd know all about the hlist stuff too :)

> Does DOS really allow nested findfirst?

Not sure about plain DOS, but there are LFN versions that do, and specifically there's a FindClose() to tidy up afterwards.

> is "no more files" a valid terminator sign?

I would say mostly yes, because as far as I know there's no going backwards through the list, so if you get 'no more files' what else could you do with the list. I do wonder however in the case of FindFirst() without wildcards, whether the caller would actually bother to do the second FindNext() just to get the No more files back, possibly this could lead us to have empty and stale hlists left around.

> why not to use DTA instead?

I figured that hlists existed only to hold a snapshot of the directory contents at the point of FindFirst(), so that although the live contents might change due to other processes etc, the data returned to FindNext() would be consistent, if not current. *BUT* I may be totally wrong on that!

And finally I have no evidence that this is what is causing F3 to fail, so it's probably not worth the rewrite of hlists as it may not even fix the problem.

**Comment by stsp** [comment]
> Not sure about plain DOS, but there are LFN versions that do

Yes but since it returns the search handle,
it doesn't need to be stacked. The stacks would
still be unneeded.

> I would say mostly yes, because as far as I know there's
> no going backwards through the list, so if you get 'no more files'
> what else could you do with the list.

But do you have any evidence that "no more files"
actually resumes the previous search? Like pops it
from the stack? Even though I see this in an mfs
code and you claim it to be correct, I still can't believe
that unless the evidence is stronger than just some
old crappy dosemu code. Have you tried that with
a test-case on hdimage?
Or maybe I am still missing the use of those hlists?

> that although the live contents might change due
> to other processes etc, the data returned to FindNext()
> would be consistent, if not current.

And why do you think this is correct?
Do you think if the prog is creating the pattern-matching
files after findfirst, they will not pop up in findnext?
Why? What kind of a consistency is that?

> so it's probably not worth the rewrite of hlists

I think people here are under delusions,  but
maybe its me. :) I think the test-case can tell the
truth.

**Comment by andrewbird** [comment]
I did a little more investigation on this a month ago and wanted to note an observation so that it doesn't get lost, but I'm not actually working on it at the moment.

When pressing F3 on a file hosted on MFS I notice that the DTA is set by NDN, but when the file contents are read a different DTA address is used.
~~~
MFS: hlist_pop: 2 popping=1 PSP=9158                                            
MFS: hlist_pop: popped list not empty?!                                         
MFS: hlist_pop: 1 poped=1 PSP=9158                                              
MFS: Finished dos_fs_redirect                                                   
                                                                                
## Set DTA to DS:DX << 8be1:0000                                                
                                                                                
INT21 at fc00:01e9: AX=1a2b, BX=0000, CX=0000, DX=0000, DS=8be1, ES=0a7f        
INT21 at fc00:01e9: AX=716c, BX=0040, CX=0000, DX=0001, DS=2ba9, ES=0000        
INT21 at fc00:01e9: AX=3d40, BX=8354, CX=0000, DX=0000, DS=28c2, ES=0a73        
INT21: open file "C:\test_mfs.bat"                                              
INT2F at fc00:01e9: AX=1123, BX=08b6, CX=08b6, DX=03be, DS=28c2, ES=00d8        
MFS: Entering dos_fs_redirect, FN=23                                            
INT2F at fc00:01e9: AX=1203, BX=08b6, CX=08b6, DX=03be, DS=28c2, ES=00d8        
MFS: selecting drive fn=23                                                      
MFS: FNX=C:\test_mfs.bat                                                        
MFS: selected drive 2: /clients/common/dosemu2.git/test-imagedir/dXXXXs/c/      
INT2F at fc00:01e9: AX=1116, BX=2ed5, CX=0000, DX=01be, DS=00d8, ES=00d8        
MFS: Entering dos_fs_redirect, FN=16                                            
INT2F at fc00:01e9: AX=1203, BX=2ed5, CX=0000, DX=01be, DS=00d8, ES=00d8        
MFS: selecting drive fn=16                                                      
MFS: sda filename1 = 'C:\TEST_MFS.BAT'                                          
MFS: selected drive 2: /clients/common/dosemu2.git/test-imagedir/dXXXXs/c/      
MFS: (mode = 0x0040)                                                            
MFS: (sft_open_mode = 0x0040)                                                   
MFS: Open existing file C:\TEST_MFS.BAT                                         
MFS: dos_fs: build_ufs_path for DOS path 'C:\TEST_MFS.BAT'                      
MFS: dos_gen: ufs '/clients/common/dosemu2.git/test-imagedir/dXXXXs/c/', path '\TEST_MFS.BAT', l=51
MFS: dos_gen: path_to_ufs '/clients/common/dosemu2.git/test-imagedir/dXXXXs/c//test_mfs.bat'
MFS: dos_fs: build_ufs_path result is '/clients/common/dosemu2.git/test-imagedir/dXXXXs/c/test_mfs.bat'
MFS: auspr 'C:\TEST_MFS.BAT'                                                    
MFS: auspr(TEST_MFS.BAT,TEST_MFS,BAT)                                           
MFS: is_msdos_device /clients/common/dosemu2.git/test-imagedir/dXXXXs/c/test_mfs.bat
MFS: find file /clients/common/dosemu2.git/test-imagedir/dXXXXs/c/test_mfs.bat  
MFS: is_msdos_device /clients/common/dosemu2.git/test-imagedir/dXXXXs/c/test_mfs.bat
MFS: file exists as is                                                          
MFS: Large file locking start=100000000, len=1                                  
MFS: open succeeds: '/clients/common/dosemu2.git/test-imagedir/dXXXXs/c/test_mfs.bat' fd = 0x21
MFS: Size : 31                                                                  
MFS: Finished dos_fs_redirect                                                   
INT21 at fc00:01e9: AX=3f00, BX=0006, CX=0200, DX=0000, DS=28c2, ES=0000        
INT2F at fc00:01e9: AX=1108, BX=29f6, CX=0200, DX=01be, DS=00d8, ES=00d8        
MFS: Entering dos_fs_redirect, FN=08                                            
INT2F at fc00:01e9: AX=1203, BX=29f6, CX=0200, DX=01be, DS=00d8, ES=00d8        
MFS: selecting drive fn=8                                                       
MFS: selected drive 2: /clients/common/dosemu2.git/test-imagedir/dXXXXs/c/      
                                                                                
## But DTA in file read is 0x28c2:0000                                          
MFS: Read file fd=21, dta=0x28c20, cnt=512                                      
MFS: Read file pos = 0                                                          
MFS: Handle cnt 1                                                               
MFS: Actual pos 0                                                               
MFS: Read returned : 31                                                         
MFS: Read file pos after = 31                                                   
MFS: Finished dos_fs_redirect                                                   
~~~

Since NDN is a DPMI program I wonder if `src/dosext/dpmi/msdos/msdos.c` is interacting somehow with this value, but my knowledge on DPMI is very limited.

When comparing the same F3 logs between MFS and FATFS hosted file I see
  - MFS : file is read totally, then as if NDN didn't get all of it, it's read again from offset 1, then 2 etc.
  - FATFS : file is read totally, then NDN carries on to preview it

**Comment by stsp** [comment]
Yes, an interesting observation, and of
course msdos.c does interact with dta.
But it shouldn't be any different with
reading from fat, so if there dta changes
the same way, there is nothing interesting.

I think its time to offer a bounty for this
ticket. I'll send 100$ to any one who
fixes this. :)

**Comment by andrewbird** [comment]
Now you have more logging output with interrupt return registers, comparing a FATFS and an MFS log is better as they remain more in sync. I can see, as you did right at the start of this ticket, that they diverge when attempting to `findfirst d:\\test.fil\????????.???` I wrote some tests to checkout the return values from findfirst. See https://travis-ci.com/andrewbird/dosemu2/builds/143035918 I can see that in the case a path component is missing on FATFS the return code is 0x03 (PATH NOT FOUND) but on MFS it's 0x12 (NO MORE FILES), I suspect this is the problem with NDN.

#### FATFS
~~~
int 0x21, ax=0x4e00                                                             
int 0x21, ax=0x4e00                                                             
RET INT0xe6 eax=0x00004e00 ebx=0x00000000 ss=0x2413 esp=0x000007ee              
           ecx=0x0000003f edx=0x00000200 ds=0x230c  cs=0xf000 ip=0xf6ce         
           esi=0x00000000 edi=0x00000000 es=0x0000 flg=0x00030046               
RET INT0x16 eax=0x00001100 ebx=0x0000035a ss=0x00da esp=0x000008e0              
           ecx=0x00000006 edx=0x00000000 ds=0x00da  cs=0x0070 ip=0x018c         
           esi=0x0000063a edi=0x000003b6 es=0x00da flg=0x000b0246               
MFS: dos_fs_redirect entering, FN=23, ^[[94m'Qualify filename'^[[0m             
int 0x2f, ax=0x1203                                                             
MFS: selecting drive                                                            
MFS: select_drive() DS:SI = 'C:\test_mfs.bat\*.*'                               
MFS: no drive selected fn=23                                                    
MFS: dos_fs_redirect finished [^[[94mREDIRECT^[[0m]                             
RET INT0x2f eax=0x00001123 ebx=0x00000000 ss=0x00da esp=0x000008f6              
           ecx=0x00000000 edx=0x00000000 ds=0x232c  cs=0x0754 ip=0x077e         
           esi=0x00000000 edi=0x000003be es=0x00da flg=0x00030093               
iret INT0x21 eax=0x00000003 ebx=0x00000000 ss=0x2413 esp=0x000007fc             
           ecx=0x0000003f edx=0x00000200 ds=0x230c  cs=0xf000 ip=0xf50b         
           esi=0x00000000 edi=0x00000000 es=0x0000 flg=0x00030047               
~~~
See the error code is 0x3

#### MFS
~~~
int 0x21, ax=0x4e00                                                             
int 0x21, ax=0x4e00                                                             
RET INT0xe6 eax=0x00004e00 ebx=0x00000000 ss=0x2413 esp=0x000007ee              
           ecx=0x0000003f edx=0x00000200 ds=0x230c  cs=0xf000 ip=0xf6ce         
           esi=0x00000000 edi=0x00000000 es=0x0000 flg=0x00030046               
RET INT0x16 eax=0x00001100 ebx=0x0000035a ss=0x00da esp=0x000008e0              
           ecx=0x00000006 edx=0x00000000 ds=0x00da  cs=0x0070 ip=0x018c         
           esi=0x0000063a edi=0x000003b6 es=0x00da flg=0x000b0246               
MFS: dos_fs_redirect entering, FN=23, ^[[94m'Qualify filename'^[[0m             
int 0x2f, ax=0x1203                                                             
MFS: selecting drive                                                            
MFS: select_drive() DS:SI = 'C:\test_mfs.bat\*.*'                               
MFS: selected drive 2: /clients/common/dosemu2.git/test-imagedir/dXXXXs/c/      
MFS: dos_fs_redirect finished [^[[94mREDIRECT^[[0m]                             
RET INT0x2f eax=0x00001123 ebx=0x00000000 ss=0x00da esp=0x000008f6              
           ecx=0x00000000 edx=0x00000000 ds=0x232c  cs=0x0754 ip=0x077e         
           esi=0x00000000 edi=0x000003be es=0x00da flg=0x00030093               
MFS: dos_fs_redirect entering, FN=1B, ^[[94m'Find file'^[[0m                    
int 0x2f, ax=0x1203                                                             
MFS: selecting drive                                                            
MFS: select_drive() sda_filename1 = 'C:\TEST_MFS.BAT\????????.???'              
MFS: selected drive 2: /clients/common/dosemu2.git/test-imagedir/dXXXXs/c/      
MFS: findfirst C:\TEST_MFS.BAT\????????.??? attr=3f                             
MFS: dos_fs: build_ufs_path for DOS path 'C:\TEST_MFS.BAT\????????.???'         
MFS: dos_gen: ufs '/clients/common/dosemu2.git/test-imagedir/dXXXXs/c/', path '\TEST_MFS.BAT\????????.???', l=51
MFS: dos_gen: path_to_ufs '/clients/common/dosemu2.git/test-imagedir/dXXXXs/c//test_mfs.bat/????????.???'
MFS: dos_fs: build_ufs_path result is '/clients/common/dosemu2.git/test-imagedir/dXXXXs/c/test_mfs.bat/????????.???'
MFS: auspr 'C:\TEST_MFS.BAT\????????.???'                                       
MFS: auspr(????????.???,????????,???)                                           
MFS: Find first ????????.???                                                    
MFS: is_msdos_device /clients/common/dosemu2.git/test-imagedir/dXXXXs/c/test_mfs.bat/
MFS: find file /clients/common/dosemu2.git/test-imagedir/dXXXXs/c/test_mfs.bat/ 
MFS: is_msdos_device /clients/common/dosemu2.git/test-imagedir/dXXXXs/c/test_mfs.bat/
MFS: find_file(): not a directory: /clients/common/dosemu2.git/test-imagedir/dXXXXs/c/test_mfs.bat
MFS: dos_fs_redirect finished [^[[91mERROR 0x12^[[0m]                           
RET INT0x2f eax=0x00000012 ebx=0x00000978 ss=0x00da esp=0x000008fc              
           ecx=0x00000000 edx=0x000000b0 ds=0x00da  cs=0x0754 ip=0x06d6         
           esi=0x00000754 edi=0x000000b0 es=0x0632 flg=0x000b0293               
iret INT0x21 eax=0x00000012 ebx=0x00000000 ss=0x2413 esp=0x000007fc             
           ecx=0x0000003f edx=0x00000200 ds=0x230c  cs=0xf000 ip=0xf50b         
           esi=0x00000000 edi=0x00000000 es=0x0000 flg=0x00030047               
~~~
See the error in ax is 0x12

In the redirector that appears to come from `mfs.c:find_file()`, but that function is used all over the place, so I'm wary of altering it. BTW I'm not interested in the bounty, so I'll be happy if you or I fix it

**Comment by stsp** [comment]
And I don't mind giving it to anyone.
Anyone can later refuse. :)

**Comment by stsp** [comment]
You can do copy/paste of that function as a quick check.

**Comment by andrewbird** [comment]
Whoo!
![ndn-view](https://user-images.githubusercontent.com/220835/71770894-a5804400-2f2a-11ea-9ae0-317f37089138.png)

So it seems the problem is that the error code that's optionally returned by `find_file()` is being discarded in `get_dir()`.  This rough patch makes it work, but some tidying is necessary
```C
index 504ce29ae..d6e5489de 100644
--- a/src/dosext/mfs/mfs.c
+++ b/src/dosext/mfs/mfs.c
@@ -1342,7 +1342,7 @@ static int convert_compare(const char *d_name, char *fname, char *fext,
    mext = DOS (uppercase) extension to match (can have wildcards)
    drive = drive on which the directory lives
 */
-static struct dir_list *get_dir(char *name, char *mname, char *mext, int drive)
+static struct dir_list *get_dir(char *name, char *mname, char *mext, int drive, int *doserror)
 {
   struct mfs_dir *cur_dir;
   struct mfs_dirent *cur_ent;
@@ -1353,12 +1353,20 @@ static struct dir_list *get_dir(char *name, char *mname, char *mext, int drive)
   char fname[8];
   char fext[3];
 
-  if(is_dos_device(name) || !find_file(name, &sbuf, drive, NULL))
+  if (is_dos_device(name)) {
+    if (doserror)
+      *doserror = NO_MORE_FILES;
+    return NULL;
+  }
+
+  if (!find_file(name, &sbuf, drive, doserror))
     return NULL;
 
   if ((cur_dir = dos_opendir(name)) == NULL) {
     Debug0((dbg_fd, "get_dir(): couldn't open '%s' errno = %s\n", name, strerror(errno)));
-    return (NULL);
+    if (doserror)
+      *doserror = NO_MORE_FILES;
+    return NULL;
   }
 
   Debug0((dbg_fd, "get_dir() opened '%s'\n", name));
@@ -1385,7 +1393,9 @@ static struct dir_list *get_dir(char *name, char *mname, char *mext, int drive)
     entry->attr = get_dos_attr(NULL,entry->mode,entry->hidden);
 
     dos_closedir(cur_dir);
-    return (dir_list);
+    if (!dir_list && doserror)
+      *doserror = NO_MORE_FILES;
+    return dir_list;
   }
   /* for efficiency we don't read everything if there are no wildcards */
   else if (mname && !memchr(mname, '?', 8) && !memchr(mext, '?', 3))
@@ -1406,7 +1416,9 @@ static struct dir_list *get_dir(char *name, char *mname, char *mext, int drive)
       entry->attr = get_dos_attr(buf,entry->mode,entry->hidden);
     }
     dos_closedir(cur_dir);
-    return (dir_list);
+    if (!dir_list && doserror)
+      *doserror = NO_MORE_FILES;
+    return dir_list;
   }
   else {
     int is_root = (strlen(name) == drives[drive].root_len);
@@ -1449,7 +1461,9 @@ static struct dir_list *get_dir(char *name, char *mname, char *mext, int drive)
     }
   }
   dos_closedir(cur_dir);
-  return (dir_list);
+  if (!dir_list && doserror)
+    *doserror = NO_MORE_FILES;
+  return dir_list;
 }
 
 /*
@@ -2116,7 +2130,8 @@ int find_file(char *fpath, struct stat * st, int drive, int *doserrno)
       Debug0((dbg_fd, "find_file(): not a directory: %s\n", fpath));
       if (slash2)
        *slash2 = '/';
-      if (doserrno) *doserrno = PATH_NOT_FOUND;
+      if (doserrno)
+        *doserrno = PATH_NOT_FOUND;
       return (FALSE);
     }
     else {
@@ -3436,6 +3451,7 @@ static int dos_fs_redirect(struct vm86_regs *state)
   int hlist_index;
   int doserrno = FILE_NOT_FOUND;
   uint16_t dosdataseg;
+  int doserror;
 #if 0
   static char last_find_name[8] = "";
   static char last_find_ext[3] = "";
@@ -3797,7 +3813,7 @@ static int dos_fs_redirect(struct vm86_regs *state)
       build_ufs_path(fpath, filename1, drive);
       bs_pos = getbasename(fpath);
       *bs_pos = '\0';
-      dir_list = get_dir(fpath, fname, fext, drive);
+      dir_list = get_dir(fpath, fname, fext, drive, NULL);
       if (!dir_list) {
         SETWORD(&(state->eax), PATH_NOT_FOUND);
         return FALSE;
@@ -3840,8 +3856,7 @@ static int dos_fs_redirect(struct vm86_regs *state)
 
       bs_pos = getbasename(fpath);
       *bs_pos = '\0';
-      dir_list = get_dir(fpath, fname, fext, drive);
-
+      dir_list = get_dir(fpath, fname, fext, drive, NULL);
       if (dir_list == NULL) {
         build_ufs_path(fpath, filename1, drive);
         if (!find_file(fpath, &st, drive, &doserrno)) {
@@ -4149,18 +4164,21 @@ do_create_truncate:
          */
       }
 
+      Debug0((dbg_fd, "AJB01\n"));
       bs_pos = getbasename(fpath);
       *bs_pos = '\0';
       /* for efficiency we don't read everything if there are no wildcards */
       if (!memchr(sdb_template_name(sdb), '?', 8) && !memchr(sdb_template_ext(sdb), '?', 3)) {
-        hlist = get_dir(fpath, sdb_template_name(sdb), sdb_template_ext(sdb), drive);
+        hlist = get_dir(fpath, sdb_template_name(sdb), sdb_template_ext(sdb), drive, &doserror);
         bs_pos = NULL;
       } else
-        hlist = get_dir(fpath, NULL, NULL, drive);
+        hlist = get_dir(fpath, NULL, NULL, drive, &doserror);
+
       if (hlist == NULL) {
-        SETWORD(&(state->eax), NO_MORE_FILES);
+        SETWORD(&(state->eax), doserror);
         return FALSE;
       }
+
```

**Comment by stsp** [comment]
Yep, great finding!

```
   int doserrno = FILE_NOT_FOUND;
   uint16_t dosdataseg;
+  int doserror;
```

Isn't both `doserror` and `doserrno` too much?

**Comment by andrewbird** [comment]
Sure, poor naming. I'm not sure about the correct fix yet though.

**Comment by stsp** [comment]
Seems to work!
Please send me privately the data
for sending 100$. :)
