### ISSUE TITLE
lredir2 -d c: changes directory listing

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#362]
Try these commands in a fresh dosemu2 session:
```
dir
lredir2 -d c:
dir
```
The output will be different. The sorting changes and @stsp noticed that long file names are missing.

**Comment by andrewbird** [comment]
So without evidence to the contrary, I'm assuming the first dir is on an mfs network drive and the second on a fatfs virtual drive made from the same directory. If so, neither observation surprises me. The mfs drive, depending upon DOS version, probably gets the long filename service provided by dosemu. The mfs drive will also build the directory list with no regard to the DOS listing semantics. On the other hand as far as I know fatfs doesn't provide VFAT filesystem, only FAT, and so DOS wouldn't be able to generate long filenames itself. Additionally dosemu's fatfs spends some time altering the order of the files in the directory so that certain special files IO.SYS, MSDOS.SYS etc appear in the places DOS expect them to. Otherwise DOS wouldn't be able to boot from fatfs drives.

**Comment by stsp** [comment]
I think long file names can't just disappear.
It would be much better if they transform to SFN.
Given that dir lists sfns by default, there shouldn't
be missing files IMHO.

**Comment by stsp** [comment]
I mean, this:
`@stsp noticed that long file names are missing.`
should read as
`@stsp noticed that long file names are missing along
with the short ones`.

**Comment by andrewbird** [comment]
Were the files that disappeared present when the fatfs drive was created?

**Comment by stsp** [comment]
Yes, sure.

**Comment by stsp** [comment]
All long files disappear.

**Comment by andrewbird** [comment]
Well I think the problem is not with the lredir2 -d, but that the fatfs drive never adds files with long filenames. I manually tweaked the source to not lredir the drives, then did the following:
~~~
D:\>dir
 
 Volume in drive D is DRIVES D
 Volume Serial Number is 4ADD-1B8B
 Directory of D:\
 
File not found
                       10,612,736 bytes free
 
D:\>lredir2 d: LINUX\FS/clients/common/dosemu2.git/test-imagedir/drives/d
D: = LINUX\FS/CLIENTS/COMMON/DOSEMU2.GIT/TEST-IMAGEDIR/DRIVES/D attrib = READ/WR
ITE
 
D:\>dir
 
 Volume in drive D is ir/drives/d
 Directory of D:\
 
SPACE~L# TXT            14  04-16-17  22:36 space embedded filename.txt
VERYL~3G TXT            14  04-16-17  22:36 verylongfilename.txt
SHRTN~!5 LON            14  04-16-17  22:36 shrtname.longextension
         3 file(s)             42 bytes
         0 dir(s)       57,568.50 MB free
~~~

**Comment by andrewbird** [comment]
To make these files accessible I guess either VFAT support needs adding, or to name mangle them into 8.3 format. For the latter probably the mangling routines from mfs could be relocated and reused.

**Comment by stsp** [comment]
Of course we don't need VFAT just for that.
Mangling to sfn sounds much more plausible.
