### ISSUE TITLE
fails on ubuntu14.04: cannot load libbfd-2.26.1-system.so

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#408]
I did make deb on ubuntu 16.04 and then installed on ubuntu 14.04.

Executing dosemu2 on ubuntu 14.04 gives this error:

`/usr/bin/dosemu.bin: error while loading shared libraries: libbfd-2.26.1-system.so: cannot open shared object file: No such file or directory`

Locate libbfd result:

```
spectra@spectra-media-server:~/master/dosemu2/64bits$ locate libbfd
/usr/lib/libbfd-2.24-system.so
/usr/lib/libbfd.a
/usr/lib/libbfd.so


```
My workaround is making a softlink /usr/lib/libbfd-2.24-system.so to libbfd-2.26.1-system.so :

`sudo ln -s /usr/lib/libbfd-2.24-system.so /usr/lib/libbfd-2.26.1-system.so`

**Comment by stuaxo** [comment]
This is likely when building a deb on a newer distro.

You might be able to setup a chroot or docker instance running 14.04 and do the build from there to make something that will work from the older version.

**Comment by stsp** [comment]
> I did make deb on ubuntu 16.04 and then installed on ubuntu 14.04.

Yes, its a bug: I put `${shlibs:Depends}` to `Recommends:`, not
to `Depends:`. But part of it, like libbfd, should go to `Depends:`.
I don't know how to fix this unless we can split `${shlibs:Depends}`
by patterns, etc.

For now, please just don't do that!
Use daily builds for any old version from here:
https://code.launchpad.net/~dosemu2/+recipe/dosemu2-daily

**Comment by bpranoto** [comment]
Downloaded and installed dosemu2_2.0-pre7-4550+55e7188-ubuntu14.04.1_i386.deb

It fails to run:
```
spectra@spectra-media-server:~/master/dosemu2/64bits$ dosemu
/usr/bin/dosemu.bin: error while loading shared libraries: libbfd-2.24-system.so: wrong ELF class: ELFCLASS64
```
BTW, the ubuntu version is 14.04.5

**Comment by andrewbird** [comment]
I'm assuming your machine is 32bit (i386) since from what I can see you have installed the 32 bit package, but your system seems to have some 64 bit version of libbfd on it. Your other 16.04 machine where you attempted to build earlier has a directory called 64bit, which confuses me slightly though

Just running the same locate command on my 32bit 16.04 systems shows the bfd library files installed in an arch specific directory not plain /usr /lib

32bit 16.04
~~~
ajb@polly:~$ locate libbfd
/usr/lib/i386-linux-gnu/libbfd-2.26-armel.so
/usr/lib/i386-linux-gnu/libbfd-2.26-system.so
/usr/lib/i386-linux-gnu/libbfd-2.26.1-armel.so
/usr/lib/i386-linux-gnu/libbfd-2.26.1-system.so
/usr/lib/i386-linux-gnu/libbfd.a
/usr/lib/i386-linux-gnu/libbfd.so
~~~

The standard binutils package should provide them
~~~
root@polly:~# dpkg -L binutils | grep libbfd
/usr/lib/i386-linux-gnu/libbfd-2.26.1-system.so
/usr/lib/i386-linux-gnu/libbfd-2.26-system.so
~~~

Why not see if the file in /usr/lib is owned by a package (change path for your 64bit file)
~~~
root@polly:~# dpkg -S /usr/lib/i386-linux-gnu/libbfd-2.26-system.so
binutils: /usr/lib/i386-linux-gnu/libbfd-2.26-system.so
~~~

So from what i can see, you've either got
a) 32bit system, 32bit dosemu, and a rogue 64 bit library of libbfd in /usr/lib
or
b) 64bit system, 32bit dosemu package installled (is this even possible?)

**Comment by bpranoto** [comment]
My fault. I downloaded wrong package. The target system is indeed 64bit. I don't have access to the target computer right now, will try later. Sorry...

**Comment by stsp** [comment]
I added the question at askubuntu.com:
https://askubuntu.com/questions/936480/dpkg-is-it-ipossible-to-split-shlibsdepends
Maybe someone can suggest a fix or a
work-around.

**Comment by stsp** [comment]
Stephen Kitt suggested the `override_dh_shlibdeps:`
trick. So this should be easy to fix once I get to the
ubuntu machine.
