### ISSUE TITLE
put himem.sys in?

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#413]
Just a topic for discussion.
Since we are at changing config.sys etc,
I am also thinking about adding himem.sys
by default. Not that it helps a lot, but users
do not even know this works. So putting it in
by default has a good fate of hinting users
that we support native himem.sys. :)
What do people think about that?

**Comment by andrewbird** [comment]
Is there any reason a user would want to run without it, or install the one that came with DOS?

**Comment by stsp** [comment]
Such reasons frequently pop up, but
@jschwartzenberg immediately reports
them as bugs. :) Also Eric Auer says that
himem.sys of freedos is not perfect and
comes in many different versions from
different sources.
So I guess I will do the change only for
the ms-dos's config.sys template and
leave the fdconfig.sys alone.

**Comment by jschwartzenberg** [comment]
I just report based on what @stsp says should/shouldn't work ;)
Unfortunately I have very little time to test now. This should be automated.

I think it should only be in by default if it really helps with compatibility. Otherwise it doesn't make sense. It could also be put in with a config.sys menu like FreeDOS ships with by default. That menu is not extremely user-friendly though. There could also be different config.sys profiles based on the file extension. It could then be possible to switch between those using a command-line option or environment variable.

**Comment by stsp** [comment]
OK, so I added it only to ms-dos config.sys
template, leaving the default as-is.
