### ISSUE TITLE
Not disabling SIGALTSTACK_WA, update your kernel - on 32bit 4.11.0 kernel - why?

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#420]
I'm seeing this, as I have for a while, but now I have kernel 4.11.0 (Ubuntu 32bit 14.04 HWE) I thought it would go away. Is there a way to detect kernel support for SS_AUTODISARM at run time, as it seems strange that the build machine kernel should influence the use of the workaround?

~~~
signal.c:56:10: warning: #warning Not disabling SIGALTSTACK_WA, update your kernel [-Wcpp]
         #warning Not disabling SIGALTSTACK_WA, update your kernel
~~~

**Comment by stsp** [comment]
This warning is only enabled for
development builds. It means that
it wasn't able to make sure at compile-time
that you have the needed functionality,
so it deferred the detection to run-time.
These days glibc prevents the compile-time
detection by not exporting the needed
flags, but the run-time detection should
work nevertheless.
This warning is needed so that people
to ping the glibc devs about this from
time to time. Users who compile non-devel
builds, will not see it.
You can also specify `NOWARN_UNDISABLED_WA=1`
when running `configure` to get rid of
that. Do you still think something is
needed to silence it even more?

**Comment by andrewbird** [comment]
Okay, nothing to worry about then.
