### ISSUE TITLE
File or directory creation on hdimage fails

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#443]
WIth a C: drive redirection from ~/.dosemu/drives/c, the following commands access the image so that drive D: mounts to the contained partition.

```
touch dummy.dat
mkfatimage16 -k 10240 -p -f dummy.img dummy.dat
dosemu -X -I"disk { hdimage \"$PWD/dummy.img\"}"
```

When I switch the current drive to D: and enter "mkdir test" or "echo > test", both fail. However, using "del dummy.dat" I can delete an existing file.

I'm using dosemu-2.0pre7.1-20170823-63-g2b3a1cbc on Debian 9.1

**Comment by ecm-pushbx** [comment]
Here's the output of the failing commands. Ignore the weird strings in the prompt, that's most likely a different issue.
```
D:\F6╚=/≤]6╣◄ù2ê6└≤ë>mkdir test
MKDIR failed for 'test'.
D:\F6╚=/≤]6╣◄ù2ê6└≤ë>echo > test
Can not redirect output to file 'test'.
D:\e 'test'.
2ê6└≤ë> 
```

**Comment by andrewbird** [comment]
Which version of Dos? How about rerunning with -D+dRW and posting the boot.log,please?

**Comment by andrewbird** [comment]
I recreated your test here using MS-DOS 3.30 (I use local dosemu.conf and test directories so I can run from the build directory), and it works fine for me. 
dosemu.conf
~~~
$_lpt1 = ""
$_hdimage = "drives/c:hdtype1 drives/d.img"
$_floppy_a = ""
$_bootdrive = "c"
~~~
~~~
touch dummy.dat
mkfatimage16 -k 10240 -p -f test-imagedir/drives/d.img dummy.dat
bin/dosemu.bin -n -f test-imagedir/dosemu.conf --Fimagedir test-imagedir -o test.log -D+dRW
~~~

~~~
C:\>d:
 
D:\>dir
 
 Volume in drive D has no label
 Directory of  D:\
 
DUMMY    DAT        0   9-02-85   9:14a
        1 File(s)  10477568 bytes free
 
D:\>mkdir test
 
D:\>echo hello >hello.txt
 
D:\>dir
 
 Volume in drive D has no label
 Directory of  D:\
 
DUMMY    DAT        0   9-02-85   9:14a
TEST         <DIR>      9-02-17   9:33a
HELLO    TXT        8   9-02-17   9:34a
        3 File(s)  10469376 bytes free
~~~

Coupled with the prompt corruption (assuming $p$g) it really looks like your DOS doesn't understand the fat filesystem created by mkfatimage16. Can you say what version you are using and perhaps provide a link to it, please?

**Comment by ecm-pushbx** [comment]
```
C:\>ver /r

FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
DOS version 7.10
FreeDOS kernel build 2036 cvs [version Aug 18 2006 compiled Aug 18 2006]
C:\>
```

[boot.log.zip](https://github.com/stsp/dosemu2/files/1272070/boot.log.zip)

**Comment by ecm-pushbx** [comment]
AFAIK I'm using the DOS out of dosemu-freedos-1.0-bin.tgz

**Comment by andrewbird** [comment]
Okay thanks, I can reproduce with FreeDOS 1.0
~~~
C:\>ver /r
 
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
DOS version 7.10
FreeDOS kernel build 2036 cvs [version Aug 18 2006 compiled Aug 18 2006]
C:\>d:
D:\F6╚=_ƒ]6╨▼ù2ê6≡ƒ4>dir
 Volume in drive D has no label
 Volume Serial Number is 1234-5678
 Directory of D:\
 
DUMMY    DAT             0  09-02-85  9:14a
         1 file(s)              0 bytes
         0 dir(s)      10,477,568 bytes free
D:\68 bytes free
≡ƒ4>echo hello >hello.txt
Can not redirect output to file 'hello.txt'.
D:\e 'hello.txt'.≡ƒ4>                             
~~~

**Comment by andrewbird** [comment]
Doesn't seem to be related to the filesystem format per se, as If I format with Freedos format.com the problem is still evident.

~~~
C:\>format d:
 Proceed with format (YES/NO)? YES
 Disk size: 10 Mbytes, FAT12. ***
Please enter volume label (max. 11 chars):
No label, disk will have no creation timestamp.
 Safe QuickFormatting (trying to save UnFormat data)
 
 Cluster stats: 0 used, 0 bad, 0 items, 2 last.
 Saving UNFORMAT information...
 Mirror map is 416 bytes long,  41 sectors mirrored.
 Preparing FAT area...
100 percent completed.
 
Safe QuickFormat complete.
 
    10,505,728  bytes total disk space (disk size)
    10,477,568  bytes available on disk (free clusters)
 
         4,096  bytes in each allocation unit.
         2,558 allocation units on disk.
 
 Volume Serial Number is 1915-1412
C:\>d:
D:\F6╚=_ƒ]6╨▼ù2ê6≡ƒ4>echo hello>hello.txt
Can not redirect output to file 'hello.txt'.
D:\e 'hello.txt'.≡ƒ4>
~~~

Note, I also tried with format /U and got the same effect.

**Comment by andrewbird** [comment]
I think freedos 1.0 has a problem with all our FAT based drives, if I reveal my hdtype1 fatfs C: drive I see the same effect.

~~~
C:\>lredir2
Current Drive Redirections:
C: = \\LINUX\FS\clients\common\dosemu2.git\test-imagedir\drives\c\ attrib = READ
/WRITE
cwd: /clients/common/dosemu2.git/test-imagedir/drives/c/
C:\>lredir2 -d c:
Redirection for drive C: was deleted.
C:\D6R:l‼▬>dir
 Volume in drive C is DRIVES C
 Volume Serial Number is 4ADD-1B8A
 Directory of C:\
 
KERNEL   SYS        45,341  11-30-16  7:22p
COMMAND  COM        66,945  11-30-16  7:22p
CONFIG   SYS            43  09-02-17 11:49a
AUTOEXEC BAT            76  09-02-17 11:49a
DOSEMU               <DIR>  09-02-17  9:10a
FORMAT   EXE        31,216  09-02-17 12:48p
LFNREAD  EXE       162,028  04-11-17  6:44p
TEST_MFS BAT            18  09-02-17 11:49a
VERSION  BAT            17  09-02-17 11:49a
         8 file(s)        305,684 bytes
         1 dir(s)      10,186,752 bytes free
C:\52 bytes free
≡ƒ4>
~~~

Note, I also tried using a FAT16 image file and got the same problem.

**Comment by andrewbird** [comment]
I wrote a test based on your example, ran it across my test suite and it seems the problem is evident on all versions of FreeDOS, but no others.
~~~
FAIL: Test FR-DOS-1.00 FAT12 image file D writable
FAIL: Test FR-DOS-1.10 FAT12 image file D writable
FAIL: Test FR-DOS-1.20 FAT12 image file D writable
~~~

Going to bisect now and see if we have a regression, as I can't believe that was always the case.

**Comment by stsp** [comment]
Maybe you can try more up-to-date fdkernel?

**Comment by stsp** [comment]
Ah, `FR-DOS-1.20` is the latest? :)

**Comment by andrewbird** [comment]
Just to recap, I'm seeing
- Freedos 1.0, 1.1, and 1.2 all see the problem
- Formatting the hdimage from within DOS doesn't fix it
- Uncovering the fatfs boot drive with lredir2 shows it has the problem too.
- FAT12 and FAT16 are both affected.

I'm wondering about partitioning, but let's see if I can find a good version to bisect from first

**Comment by stsp** [comment]
[kernel.zip](https://github.com/stsp/dosemu2/files/1272233/kernel.zip)

The latest kernel from git.

**Comment by andrewbird** [comment]
@stsp Here's the first bad commit, but I have no idea what where or why it messes up Freedos only

ajb@polly:/clients/common/dosemu2.git$ git bisect good
5dca7336d846891af70ca2865ebdd7e04bdc5df5 is the first bad commit
commit 5dca7336d846891af70ca2865ebdd7e04bdc5df5
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Wed Jul 19 07:02:12 2017 +0300

    int: update post_boot to employ new int_revect logic [#347]

:040000 040000 366c9c9b37b07c680ab98b9a4a4975b28f088ea4 aef4d45cc73ed76141586f994a3b823632cee3d9 M	src

**Comment by stsp** [comment]
Try `$_lfn_support = (off)`.

**Comment by stsp** [comment]
The (yet another) bug was in second-revect
logic, 5cad20e3.
The 5dca733 just seems to be the good
reproducer of many different bugs.

**Comment by andrewbird** [comment]
Yes I woke up this morning with the thought that I should try turning off lfn, but hey you've figured it out and fixed it. Great stuff, thanks :smile:

**Comment by andrewbird** [comment]
Thinking on a little about LFN here. On DOS versions that don't support LFN natively(everything but FreeDOS it would seem) we are trying to look up LFN names for hdimage file based FAT in MFS LFN cache. It probably won't hurt unless there's a match somehow, but doesn't seem right?

**Comment by stsp** [comment]
I am not sure I understand the above.

> On DOS versions that don't support LFN natively(everything but FreeDOS it would seem)

The only DOS that supports LFNs natively
is MS-DOS7+, and even that, according to
Bart, does not go to redirector.
In case of FreeDOS, its just that freecom is
taught to query LFNs.

> we are trying to look up LFN names for hdimage file based FAT in MFS LFN cache.

Could you please clarify?
I don't think we do anything about LFNs for
hdimages. You can try doslfn tsr that will
likely work fine with vfat hdimages. We
currently only support LFNs for redirected
drives. If we add vfat support to fatfs.c, then
we can also support that, but we don't have
to because doslfn will work with that fine.

> It probably won't hurt unless there's a match somehow, but doesn't seem right?

I don't think I understand. :)

**Comment by andrewbird** [comment]
In a test on MS-DOS 3.30 where c: drive is MFS, d: drive is hdimage file, it seems that although MFS is initially called to process the
~~~
D:
DIR test_dfw.bat
~~~
the MFS code rejects the request since it doesn't own the drive. Fair enough I think, so not a problem.

~~~
INT13: ax=0201 cx=0110 dx=0181                                                  
DISK 81 read [h:1,s:15,t:1](1)->09f2:0010                                       
DISK: /clients/common/dosemu2.git/test-imagedir/fat16.img: Trying to read 1 sectors at T/S/H 1/15/1+128 at pos 51328
DISK read @1/1/15 (1) -> 0x9f30 OK.                                             
MFS: Entering dos_fs_redirect, FN=23                                            
MFS: selecting drive fn=23 sda_cds=0xa6f179ef                                   
MFS: FNX=test_dfw.bat                                                           
MFS: no drive selected fn=23                                                    
MFS: Entering dos_fs_redirect, FN=23                                            
MFS: selecting drive fn=23 sda_cds=0xa6f179ef                                   
MFS: FNX=test_dfw.bat                                                           
MFS: no drive selected fn=23                                                    
MFS: Entering dos_fs_redirect, FN=23                                            
MFS: selecting drive fn=23 sda_cds=0xa6f179ef                                   
MFS: FNX=D:TEST_DFW.BAT                                                         
MFS: no drive selected fn=23                                                    
MFS: Entering dos_fs_redirect, FN=23                                            
MFS: selecting drive fn=23 sda_cds=0xa6f179ef                                   
MFS: FNX=D:\                                                                    
MFS: no drive selected fn=23                                                    
~~~

**Comment by stsp** [comment]
Maybe it ignores the (absence of the) remote
flag in CDS and calls to redirector anyway.
But whether to call LFN is up to an app, not
DOS kernel.

**Comment by andrewbird** [comment]
No, I'm not sure why that is happening, it's pure MS-DOS 3.30 command.com just doing DIR.

**Comment by stsp** [comment]
Please check if this didn't regress - I
changed the code a bit.

**Comment by ecm-pushbx** [comment]
Tested with "FreeDOS kernel - SVN (build 2042 OEM:0xfd) [compiled Sep 22 2017]" on "dosemu 2.0pre7.1-20171031-227-ga06b3b494!", test succeeds.

**Comment by ecm-pushbx** [comment]
Tested with "FreeDOS kernel - SVN (build 2042 OEM:0xfd) [compiled Sep 22 2017]" on "dosemu 2.0pre7.1-20171102-233-g6d5ca7e24", test succeeds.

**Comment by stsp** [comment]
Thanks!
