### ISSUE TITLE
Scanlines ?

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#459]
Many emulators (e.g. through retroarch) have shaders to emulate scanlines.   Is there any chance dosemu could have scanline emulation ?

Most of the DOS era was on CRT monitors and emulating scanlines allows things to look better than having really large chunky pixels when they are scaled up.

This page has an example of some of the settings for retroarch

https://github.com/RetroPie/RetroPie-Setup/wiki/Shaders-and-Smoothing

Showing it's more than just putting black lines every other line.

- Maybe it would be possible support the retroarch shaders ?

**Comment by stsp** [comment]
You can enable some filters
by setting `$_SDL_hwrend = (on)`
and `$_X_lin_filt = (on)`. We do
not have any fancy filters though
because SDL is exceptionally poor
in this area. If we wanted things
like this, we'd had to use the different
gfx lib, perhaps allegro or something
else. Since dosemu2 is not focused
on old games (dosbox does this very
well so no need to), I think basic filters
would be enough to have.

**Comment by stuaxo** [comment]
Is dosemu SDL or SDL2 ?

I think SDL2 is much more oriented toward GL renderers, so should be easier to integrate with things like shaders.

**Comment by stsp** [comment]
SDL2, but we were disappointed with
its opengl capabilities and switched to
sw rendering by default, so now we
don't even have the very basic filters
by default. We can have filters without
shaders, CPUs are quite powerful to
do the job, but SDL2 has nothing on
that front. Libs like SDL_gfx and
SDL_gpu are actually not an addons:
you need to throw away the SDL2 api
and use their API instead, they are not
to be mixed.

**Comment by stsp** [comment]
So to summarize: with SDL2 we do not
use opengl by default. It can optionally be
enabled, but will not work with some
proprietary video drivers. So we can't
rely on shaders.
It would be very good if SDL2 to provide
the filters for us: in opengl mode it could
do that with shaders, and in sw mode it
could do that on CPU. Unfortunately it
does not, and we can't easily stick them
from an outside, because SDL does
scaling for us, and this is where filters
should apply. If we do scaling by hands,
we'll fall into a stone age of `dosemu -X` -
that one still does scaling by hands, so
it is theoretically possible to stick filters
there.
Since dosemu2 is not focused on old
games, I do not consider this to be very
important, even though it would be very
good to at least have the very basic
scaling filters in sw scaling mode - currently
there are none, thanks to SDL2. Filters
can be ported from SDL_gfx to SDL2, but
the last time I looked into an SDL sw scaling
code, it was was quite different from SDL_gfx,
so porting will require some work.
If we ever find some other library that does
things better than sdl2 (SFML perhaps?),
we'll need to write the backend for it and
experiment with different things. SFML
looks much more friendly to opengl than
SDL2 is.
