### ISSUE TITLE
INSTALL isn't clear about what problems might be experienced with Linux <  3.16

### ISSUE THREAD

**Issue by dcoshea** [stsp/dosemu2#499]
The `INSTALL` file shows this requirement:

    - Linux >= 3.16 (with older version there may be some problems on x86_64)

Is any more information available, e.g. is it known what specific fixes in the kernel are needed?  I am using CentOS 7, which includes kernel 3.10, but Red Hat backport various patches from later kernels, so I don't know if I should expect problems or not.

Also, are there any particular issue #s that can be referenced here as examples of problems that have been seen with older kernels?  Even if perhaps it's not understood why 3.16 or later is required, it might be useful to be able to see if I can reproduce various issues on Red Hat's patched 3.10 kernel.

I searched for issues and couldn't find any obvious answers.

**Comment by stsp** [comment]
Kernel is a moving target.
Pre-3.16 problems are documented here:
https://htmlpreview.github.io/?https://github.com/stsp/dosemu2/blob/devel/doc/EMUfailure.html#AEN49
But since that, we had many more kernel updates.
https://www.spinics.net/lists/stable/msg160550.html
https://patchwork.kernel.org/patch/7955451/
https://patchwork.kernel.org/patch/7530511/
https://patchwork.kernel.org/patch/8320671/
https://lkml.org/lkml/2016/4/9/53

This is just from the top of my head.
I do not bother to update INSTALL these days
because most distros are very careful to be
up-to-date with kernel and glibc - with centos
being an exception from that.
Note that dosemu2 has work-arounds for
most of the above patches if missing, but some
are quite critical, like the vm86 fix.

HTH.

**Comment by stsp** [comment]
I recalled a bit more details on this topic.
https://www.codeweavers.com/support/wiki/Diag/BrokenLDT16
https://lkml.org/lkml/2014/4/11/542
As you can see from these URLs, linux
disabled 16bit segments in 3.14.
In commit 9838102e I wrote
`DPMI is not supported on your kernel ( >= 3.14 ), sorry!`
And that was supposed to be an end
of dosemu, or very close to.
Fortunately wine folks did not let this
to happen, and in linux-3.16 the DPMI
support was not only restored, but also
the so called espfix64 was implemented,
that made it much more reliable than
those <3.14.
So 3.16 was made an absolute requirement
and written to INSTALL, but you only
don't wan't 3.14 and 3.15, while 3.10
may be fine, although lacking espfix64
and many other new features.

**Comment by stsp** [comment]
I updated the docs as this may actually
be interesting to users.

**Comment by stsp** [comment]
Btw, does anyone know the minimum gcc
version we need today? I think 3.3 that is
listed in INSTALL, won't work.
