### ISSUE TITLE
Request: can we set code style to 'indent -kr -nut -i2 -cli2'?

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#514]
I'm just looking at int.c which received a dose of 'indent -kr' recently. I'm finding that mixed spaces and tabs make it difficult to fit on one line. My suggested style is one used in many places in the code, so it would fit in quite nicely with what we have already? If it's an effort to remember the options, we could add a script?

**Comment by stsp** [comment]
The problem with indenting the whole
source is that you'll lose `git blame` ability.
`int.c` was just so messed up that I couldn't
resist indenting it, so if you like, lets re-indent
it again.

**Comment by stsp** [comment]
OTOH `git blame` has `-w` so maybe we
can indeed survive the whole re-indent...
Not sure, really.

**Comment by stsp** [comment]
What other people think? Will re-indent hurt?
Bart?

**Comment by andrewbird** [comment]
Oh I don't really want to reindent the whole code, just that it be okay that I can write new in this style and reindent single functions where necessary.

**Comment by stsp** [comment]
Reindent single functions should go
in a separate commit, otherwise difficult
to review.
In principle, maybe we could enforce
some coding style by adding a post-commit
hook that will make sure every new commit
is indented the way we want. But I am not
sure if post-commit hooks can be made
clonable, so that people to get them automatically.
Anyway, this is probably a long story. :)

**Comment by andrewbird** [comment]
Yes, I like the idea of a separate commit to reindent a function if necessary. Shall I write a simple CONTRIBUTING.md?

**Comment by stsp** [comment]
If you like. :)

**Comment by andrewbird** [comment]
Sorry I forgot to add the fixes number to the PR commit.
