### ISSUE TITLE
rename with wildcards doesn't work with non-free doses

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#526]
This is the reason why MOS build fails.
Things like `ren a.txt *.bbb` are broken.

**Comment by stsp** [comment]
In a separate branch I added the fix
that fixes the trivial cases, like the above one.
But something like this still breaks:
`ren aa*.* bb*.*`
and I am not sure how that should be
fixed. It seems DOS throws wildcards
as-is to RENAME_FILE fn. It only does
QUALIFY_FILENAME first, but I don't
think this would help much.
I would expect it to expand at least the
first wildcard by hands, but it does not.
I wonder how RENAME_FILE is supposed
to handle this.

**Comment by stsp** [comment]
It comes from this:
http://www.ctyme.com/intr/rb-2582.htm
RBIL explicitly states that wildcards are
OK for both parts. Which means to me
that this:
http://www.ctyme.com/intr/rb-4322.htm
should end up traversing the directory.
But what looks strange is how is this
handled on a non-redirected drive.
DOS probably does the dir traversing
internally, when the drive is local. And
then I wonder why it can't call the redirector
during the traversing, rather to throw
the wildcards on it?

**Comment by stsp** [comment]
Here is how rename should work:
http://www.lagmonster.org/docs/DOS7/z-ren1.html
And now, is all this logic going to be
thrown to the redirector?? Impossible!
There is something wrong here.
command.com should do at least part
of the work...

**Comment by stsp** [comment]
But on freedos most things seem to work.
Seems like it doesn't throw the wildcards
to the redirector as other DOSes do. Hmm.

**Comment by stsp** [comment]
So freedos's freecom seems to be doing findfirst()
with the first wildcard, and from that expands
the second wildcard - just like the sane person
would do. But other DOSes exploit the fact that
FCB rename can accept wildcards, and it seems
they assume the redirector can do the same,
which is unexpected.

**Comment by stsp** [comment]
http://www.ctyme.com/intr/rb-4324.htm
Delete is explicitly mentioned to support
wildcards, and dosemu implements that.
So as silly as it is, we need to implement
the wildcard renaming...
Does anyone wants to? :)

**Comment by andrewbird** [comment]
It would probably be a couple of weeks before I  can look at this or even write tests, so if you want to fix first, feel free.

**Comment by stsp** [comment]
Tests are simple:
`ren xx*.* yy*.*`
on any non-free dos.
I think we should traverse this bugzilla
and create the status pages for different
dosemu components. For example mfs
seems to be blamed in many tickets, but
there are too many of them to find anything
useful. Same with PIC, cpuemu etc.

**Comment by bartoldeman** [comment]
Things are a bit simpler than they seem because you only need to deal with question marks (*s have been expanded already) And I believe only within the same directory. It is all fcb legacy. FcbRename in freedos fcbfns.c needs to do it too. But freedos does not pass wildcards to the redirector... I had no idea it could.

**Comment by stsp** [comment]
Yes, I already figured this boils
down to get_dir(), which seems to
support wildcards. But I won't have
time to code this up within the next
few days or more.

> I had no idea it could.

And I had no idea it should!
When you operate on non-redirected
drive, you need the code inside DOS
that does the dir traversal. Why not to
use the very same code for the remote
drive, and instead throw wildcards to
the redirector - is a big question...
Freedos is good of not doing this, but...

**Comment by andrewbird** [comment]
So I started thinking about adding some MFS SFN/LFN tests for rename. I want to test the individual int21 calls, rather than depend upon however command.com's rename is implemented on each version of DOS. I think this will reduce the chaff in the log file in the event of failure and be it be more obvious what's going wrong. For example on PC-DOS 7 I did a simple 'rename file.a file.b' and according to the log I was seeing LFN calls, so I want to avoid that.
I'm thinking of implementing tests for:
- int21/17  DOS 1 FCB rename with wildcards
- int21/56  DOS 2 rename with paths (no wildcards)
- int21/7156  LFN rename with paths (no wildcards)

Not too sure at the moment how the int21/5d00 server call interacts with the latter two to make wildcards work.

Tests will be gnu assembler for ease of modification and controllability. Any examples you have would kickstart this effort. :smile:

**Comment by stsp** [comment]
Why testing no-woldcard? Are they suppose
to fail? :)
Why assembler, and not djgpp? I think you can
do the work in C (create file etc) and then call
DOS for rename.

**Comment by andrewbird** [comment]
According to RBIL int21/56 doesn't support wildcards unless called via int21/5d00 (hence the question) so I'll test first with bare command, later move to the latter when I understand how to.

I want to see exactly what the single int21 call generates at the redirector etc, that's why I want to avoid asking command.com's rename to to the work. From what I learnt about djgpp on the previous tests, there's lots of stuff going on around the operation I want to test. That's why I wanted to use assembler. I thought about djgpp with inline asm or the int86() call from dos.h, but as it's using a flat memory model the memory accesses are awkward for seg:ofs. Watcom was considered, but since I still didn't fix my desktop computer, I didn't fancy installing it on my server machine I'm currently using.
BTW the setup (like initial file creation) and post test validation (like did the file get renamed) for the test will be done in linux using the python test runner.

**Comment by stsp** [comment]
> thought about djgpp with inline asm or the int86() call from dos.h, but as
> it's using a flat memory model the memory accesses are awkward for seg:ofs.

Better get used to it. :)
Its not really awkward as soon as you
know you can pass sel:off to int21 just
as well. Try! its magic. :)

**Comment by stsp** [comment]
Yes, 5d00 is a mystery for me.
I would expect some dedicated int2f call
for it, but there seems none.
So maybe this call just means
"throw everything possible to the redirector,
even wildcalrd", but I wonder what does it
do if the drive is local...

**Comment by stsp** [comment]
```
(DOS 3.1+) wildcards are allowed if invoked via AX=5D00h, in which case
error 12h (no more files) is returned on success
```
I would speculate that 5d00 then turns
this error into a non-error, which stands
for "it allows wildcards". But this is a wild
guess.

**Comment by andrewbird** [comment]
Will try the djgpp on the next series of tests as I finished the assembler based framework for FCB ones

**Comment by stsp** [comment]
Its certainly up to you, but please be aware
that if you want to pass DS:BX to int21, then
in inline asm you can just do:
```
movl lfn_ptr,%%ebx
/* DS is already set to 4G selector */
int $0x21
```

I mean it, you just pass the pointer to Exx
register, have DS untouched, call int21, and
it still works!

**Comment by stsp** [comment]
I applied the fix.
Review/test welcome.
