### ISSUE TITLE
DPMI error in Kernel 4.15

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#559]
````
C:\FPD26>fox.exe
DPMI is not supported on your linux kernel!

Phar Lap err 35: The 386 chip is currently executing
in virtual 8086 mode under the control of another program.  You must turn
off this other program in order to use 386|DOS-Extender to run in
protected mode.

% uname -a
Linux fujitsu 4.15.1-2-ARCH #1 SMP Sun Feb 4 22:27:45 UTC 2018 x86_64 GNU/Linux
````

Switching back to 4.14.17-1-lts makes it work again.

**Comment by stsp** [comment]
Please look into console or into boot.log
for a more detailed error and instructions
on how to proceed.

**Comment by andrewbird** [comment]
Since this problem seems to show itself between 4.14 and 4.15, perhaps it's something to do with this kernel commit [a4828f8](https://github.com/torvalds/linux/commit/a4828f81037f491b2cc986595e3a969a6eeb2fb5)?

**Comment by stsp** [comment]
No, its most likely just that some "hardening guys"
disabled the needed options again. boot.log will
contain the exact info.

**Comment by stsp** [comment]
I mean security-hardening guys in a distro.

**Comment by severach** [comment]
````
ERROR: DPMI support is not enabled on your kernel.
Make sure the following kernel options are set:
  CONFIG_MODIFY_LDT_SYSCALL=y
  CONFIG_X86_16BIT=y
  CONFIG_X86_ESPFIX64=y
````
All 3 options are no longer present in the new config. MODIFY_LDT_SYSCALL is mentioned in a comment but there's no setting for it. This smacks of the 4.0 -> 4.1 transition where they ripped out everything that ibcs needed.

**Comment by stsp** [comment]
Diddums.
Unfortunately there is nothing on our side
that can be done at a moment. But I suspect
this also breaks wine.

> All 3 options are no longer present in the new config.
> MODIFY_LDT_SYSCALL is mentioned in a comment but there's no setting for it.

The other 2 are sub-members of this one.
So when you disable this one, its sub-members
all disappear completely, while it itself becomes a comment.

**Comment by stsp** [comment]
> If DOSEMU stops working I'll need to go back to Windows.

Try fedora, it is quite open to 3-rd party
software that is not a part of it. I am using
fedora for development and so far it didn't
try to break dosemu2 unless the upstream
linux kernel does (which usually can be
undone). Also @andrewbird looks into the
ubuntu-related problems.
Don't use security-enforcing distros with
dosemu2! Dosemu2 is not for security-constrained
environments, in fact it is absolutely insecure.

**Comment by severach** [comment]
Arch isn't the problem. I can run as old of kernel as I want. The kernel team removed the settings. dosemu will stop working for all distros when they get to 4.15 unless you give some pushback.

Switching to Windows would be a long term thing when running 4.14 or less becomes impractical.

**Comment by stsp** [comment]
> The kernel team removed the settings. 

Bullsh... any proof? :)

**Comment by severach** [comment]
Bird's patch was your first warning shot. Here are the running /proc/config.gz. You can view the [config](https://git.archlinux.org/svntogit/packages.git/tree/trunk/config?h=packages/linux) used to compile.

Here are the changes

````
 CONFIG_PERF_EVENTS_INTEL_RAPL=m
 CONFIG_PERF_EVENTS_INTEL_CSTATE=m
 CONFIG_PERF_EVENTS_AMD_POWER=m
 # CONFIG_VM86 is not set
-CONFIG_X86_16BIT=y
-CONFIG_X86_ESPFIX64=y
-CONFIG_X86_VSYSCALL_EMULATION=y
+# CONFIG_X86_VSYSCALL_EMULATION is not set
 CONFIG_I8K=m
 CONFIG_MICROCODE=y
 CONFIG_MICROCODE_INTEL=y

 # CONFIG_CMDLINE_BOOL is not set
-CONFIG_MODIFY_LDT_SYSCALL=y
+# CONFIG_MODIFY_LDT_SYSCALL is not set
 CONFIG_HAVE_LIVEPATCH=y
 # CONFIG_LIVEPATCH is not set
 CONFIG_ARCH_HAS_ADD_PAGES=y
````

The "is not set" comments don't tell me what I need to turn back on to see those settings again.

[proc.config.4.14.17.gz](https://github.com/stsp/dosemu2/files/1709337/proc.config.4.14.17.gz)
[proc.config.4.15.1.gz](https://github.com/stsp/dosemu2/files/1709338/proc.config.4.15.1.gz)

**Comment by andrewbird** [comment]
From what I can see the last time MODIFY_LDT_SYSCALL Kconfig default setting in the vanilla kernel was touched was when it was added in 2015
~~~
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2349) config MODIFY_LDT_SYSCALL
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2350)      bool "Enable the LDT (local descriptor table)" if EXPERT
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2351)      default y
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2352)      ---help---
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2353)        Linux can allow user programs to install a per-process x86
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2354)        Local Descriptor Table (LDT) using the modify_ldt(2) system
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2355)        call.  This is required to run 16-bit or segmented code such as
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2356)        DOSEMU or some Wine programs.  It is also used by some very old
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2357)        threading libraries.
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2358) 
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2359)        Enabling this feature adds a small amount of overhead to
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2360)        context switches and increases the low-level kernel attack
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2361)        surface.  Disabling it removes the modify_ldt(2) system call.
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2362) 
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2363)        Saying 'N' here may make sense for embedded or server kernels.
a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2364) 
~~~

**Comment by stsp** [comment]
> a5b9e5a2f1 (Andy Lutomirski                2015-07-30 14:31:34 -0700 2351)      default y

Sure. `default y`.
No one would change that.
If some distro fiddles with config options,
then why do we care?
Don't use security-hardening distros with
dosemu2 - its an illegal and definitely a not
secure combination.

**Comment by stsp** [comment]
> The "is not set" comments don't tell me what I need to turn back on to see those settings again.

Besides rebuilding the kernel on your own,
or switching the distro - nothing.

**Comment by andrewbird** [comment]
Well I don't know Arch, but in Ubuntu if it's different to vanilla setting, then the package builder(Arch?) changed it.

**Comment by andrewbird** [comment]
Is this the Arch commit that changed it from default
https://git.archlinux.org/svntogit/packages.git/commit/trunk/config?h=packages/linux&id=9998d4fe8026c686abe8db9d9c5941d3936af3de

It looks like you need to raise a ticket with Arch

**Comment by stsp** [comment]
True but the generic suggestion is to just
not use dosemu2 with security-hardening
distros. There will be no any security this
way, so using security-hardening distro just
makes no sense.

**Comment by severach** [comment]
````
-# Linux/x86 4.14.14-1 Kernel Configuration
+# Linux/x86 4.15.0-1 Kernel Configuration
````
Those settings wern't removed by Arch. You submit a config then Linux sends back a cleaned up config with all the still valid settings and any new settings that were added by hand. Unless you can find a setting near the top changed by Arch that kills all the settings we want, those settings were removed by the Kernel team.

**Comment by stsp** [comment]
Here's the upstream defconfig of 4.15:
http://elixir.free-electrons.com/linux/v4.15.1/source/arch/x86/configs/x86_64_defconfig
As you can see, it does not alter
`CONFIG_MODIFY_LDT_SYSCALL`
Its just not there, which means the default
opt is used.
The default settings are derived from Kconfigs:
http://elixir.free-electrons.com/linux/v4.15/source/arch/x86/Kconfig#L2338
`default y`
So please, lets just stop this.
If you don't change your distro, then compile
the kernel on your own.

**Comment by severach** [comment]
https://bugs.archlinux.org/task/57440

It works. If `CONFIG_EXPERT=y` and `default y` then why does removing `CONFIG_MODIFY_LDT_SYSCALL` turn it off?

**Comment by stsp** [comment]
CONFIG_EXPERT has no influence on its value.
It only controls whether or not you can alter
that value from its default (which is 'y').
Also I don't think `CONFIG_X86_VSYSCALL_EMULATION=y`
has something to do with that.

I fully agree with the statement from their
bugzilla saying "Latter is the reason this won't happen for linux-hardened."
but not because "the syscall with the LDT opens up an not to ignore attack primitive"
but rather because dosemu2 should never
run on something security-hardened, as it
may defeat the hardening by its mere presence.

"To be fair, whoever is using dosemu2 to interface with their spaceship from the 80s or whatever is probably not doing it on Arch."
is also a fair comment.
There are plenty of general-purpose and/or
desktop distros where dosemu2 fits better.
Roughly speaking, dosemu2 should go with
the distros that are friendly to wine. Or actually
it may have an advantage over wine of not
requiring multilib, which is what wine still does.
So I wouldn't be surprised if some distro may
choose to add dosemu2 and not wine32/multilib.

This comment seems odd though:
"Would the old games/software angle be covered by a virtual machine running FreeDOS?"
dosemu2 is exactly such virtual machine!
It just does fewer sandboxing than other
VMs do, i.e. FS access is not sandboxed
to the virtual drive, network access is not
sandboxed to virtual NIC etc, but its stlll the
same thing.

**Comment by stsp** [comment]
This comment looks very strange:
"I did this myself, and note that it did add a little over 20mb to the package, which seems excessive for this feature"
It tells about enabling `CONFIG_MODIFY_LDT_SYSCALL`.
Its absolutely impossible, considering that
the packed bzImage is usually 1-2Mb and
this option does not affect modules.
So someone should test that assertion.
Maybe he mistyped "mb" instead of "Kb"? :)

**Comment by stsp** [comment]
I think maybe some distro can come up
with the security enforcements for dosemu2.
For example, the separate user can be
created for it, so that all DOS files being
in the separate home dir. That home dir
should be group-writable so that other
users can fiddle with DOS files easily,
but dosemu2 itself will then no longer
be able to access the normal user's
home dir, so it won't be able to steal
any sensitive data from the user.
