### ISSUE TITLE
cannot install on ubuntu 18.04, package xfont-utils not found

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#597]
I just installed dosemu2 on ubuntu 18.04 from https://code.launchpad.net/~dosemu2/+archive/ubuntu/ppa/+build/14802117

I got this error:
```
dpkg: dependency problems prevent configuration of dosemu2:
 dosemu2 depends on xfont-utils (>= 1:7.5+2); however:
  Package xfont-utils is not installed.

```
Could it possibly a typo? because I found package xfonts-utils installed instead.
```
akunting@akunting:~/dosemu2/18.04/64bits$ dpkg --list xfonts-utils
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  xfonts-utils   1:7.7+6      amd64        X Window System font utility prog

```

**Comment by stsp** [comment]
debuild recipe sets the deps automatically.
I only specify `Depends: ${misc:Depends}, ${shlibs:Depends}`.
And it indeed sets `Depends: xfont-utils (>= 1:7.5+2)` from
that, whereas Build-Depends has `xfonts-utils`.
So I think the bug is elsewhere.
Anyone familiar with debuild?
Maybe @skitt knows what't going on?

**Comment by skitt** [comment]
I do indeed know what’s going on; this is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894835 which causes `dh_installxfonts` to generate a dependency on `xfont-utils` instead of `xfonts-utils`. The bug is unfortunately present in the version of `debhelper` used in Ubuntu 18.04 — it might be worth filing a bug there...

**Comment by andrewbird** [comment]
I added a bug at Ubuntu's Launchpad https://bugs.launchpad.net/ubuntu/+source/debhelper/+bug/1767792

**Comment by stsp** [comment]
Thanks guys. :)

**Comment by stsp** [comment]
I am absolutely not at this subject, but,
from the user's point of view, it looks a
bit strange that debhelper hardcodes
package names instead of the packages
themselves doing so.

**Comment by skitt** [comment]
I understand that it can seem strange ;-). The idea is that packages installing X fonts can rely on `dh_installxfonts` to do the right thing: building the appropriate maintainer scripts to register and unregister the fonts, and adding the appropriate dependency. (And `dh_installxfonts` is run automatically by `debhelper`.) Maintainers themselves don’t have to worry about the details of how that happens, and in theory packages could be changed to support other installation mechanisms without any source changes, simply by updating `debhelper` and rebuilding the packages...

**Comment by stsp** [comment]
OK, I thought we get the dep on `xfont-utils`
because of `xfonts-utils` in `Build-Depends`,
but now I realize they come via `${misc:Depends}`
regardless. Then it makes sense that the bug
have nothing to do with the `xfonts-utils` package itself.
This package doesn't have any `${shlibs:Depends}`,
so it can't affect any deps by itself - that's my
current understanding. Hope its closer to reality now. :)
Thanks for info.

**Comment by bpranoto** [comment]
I installed the updated debhelper from [https://packages.debian.org/sid/all/debhelper/download](https://packages.debian.org/sid/all/debhelper/download) and now dosemu2 installed fine on ubuntu 18.04.

Shoud we close this bug report as it is not dosemu2 bug?

**Comment by stsp** [comment]
Indeed.
