### ISSUE TITLE
gawk requirement not mentioned in INSTALL file

### ISSUE THREAD

**Issue by ecm-pushbx** [stsp/dosemu2#660]
**Describe the bug**
When compiling (revision git 6d6eb7460dbb) on a newly installed Debian buster amd64 system, gawk is needed:

```
gcc -c -MMD -DCFLAGS_STR="-Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -imacros config.hh -Wno-unused-result -Wcast-qual -fplan9-extensions -Wno-maybe-uninitialized -fpie -ggdb3 -O   " -I../../../src/include -I../../../src/plugin/include -I/home/evln/coding/proj/dosemu2/src/include   -o bios.o bios.S
nm -g -n bios.o | gawk '\
	BEGIN {\
	  COUNT=0;\
	  print "// Warning: autogenerated";\
          print "";\
          print "#include \"bios.h\"";\
          print "";\
	  print "struct bios_symbol_entry bios_symbol[] = {";\
	}\
	{\
	  HEXSTR = sprintf("0x%s", $1);\
	  ADDR = strtonum(HEXSTR);\
	  if (ADDR <= 0xffff) {\
	    COUNT++;\
	    printf "  { 0x%04x, \"%s\" },\n", ADDR, $3;\
	  }\
	}\
	END {\
	  print "};";\
	  print "";\
          print "int bios_symbol_num = " COUNT ";";\
	}\
	' > bios_symbols.c
/bin/sh: 1: gawk: not found
make[2]: *** [Makefile:13: bios_symbols.c] Error 127
make[1]: *** [/home/evln/coding/proj/dosemu2/src/arch/linux/Makefile.main:118: base/bios] Error 2
make: *** [Makefile:24: default] Error 2
```

Installing gawk and compiling again does solve this. gawk should be listed in the requirements list in INSTALL.

**Comment by ecm-pushbx** [comment]
You added a check to the configuration script, but I think you should still also put it in the INSTALL file.

**Comment by stsp** [comment]
For what?

**Comment by ecm-pushbx** [comment]
Because that's the one I used to figure out what to install. And it mentions all the tool chain needed.

**Comment by stsp** [comment]
Its really not for that.
dosemu2 uses many more tools during
build, like `grep`, `sed`, `find` and all that.
`INSTALL` lists only the major libs or tools
from which the minimum version is required.
This is mostly so that the person can evaluate
if his whole distro meets the minimal reqs, and
if not - not to bother even trying to tun `configure`.
Or for people who want to migrate from gcc to
clang, or from 32bit to 64bit etc - they usually want
to know the migration details, but this, again,
only affects the specific software (i.e. you want
to know what clang will be needed for migration
or what 64bit kernel is needed, but you'll be
very surprised that you may ever need to upgrade
gawk).
It would be useless to list every tool there,
because they are already listed in rpm spec,
in debian spec and in configure script. You
simply can't maintain yet another location,
which is not even automatically checked, as
not being a part of a build process.

The problem here is likely an _optional_
dosemu2 deps. You probably was afraid
to miss some, and so you went looking
them up in `INSTALL`. Its quite bad that
we use `INSTALL` that way. It shouldn't be
listing them, but as of yet there is no other
source of such info (unless you look directly
into an rpm or deb specs of course).
Maybe the better solution would be if
configure would list the plugins that failed
to enable and tell what was missing.
Most users will ignore that (plugins are optional),
but those like you may try to install everything.
This is not absolutely trivial to implement,
in particular the main `configure` script should
then collect the errors from plugin's `configure`
scripts, to present to the user what was
actually missing. But feel free to open an
RFE for this. Build process should be user-friendly.

**Comment by ecm-pushbx** [comment]
Thanks for the explanation!

> The problem here is likely an optional dosemu2 deps. You probably was afraid to miss some, and so you went looking them up in INSTALL.

By "deps" do you mean package management dependencies? I didn't use a package at all, I only compiled from the git source repo.

**Comment by stsp** [comment]
> By "deps" do you mean package management dependencies?
> I didn't use a package at all, I only compiled from the git source repo.

You probably only compile dosemu2 while
installing other things (like gawk or sdl2)
from packages, no? So of course I meant
the package deps, but `configure` script
operates on libs and header, not on packages,
so the kind of deps doesn't matter here.
