### ISSUE TITLE
import internal command ?

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#69]
Here's an 'import' command I wrote years ago, it's the opposite of 'export' and lets you get environment variables inside DOS from outside dosemu

If it looks useful I can clean it up + try and get it included ..

http://dodgyscripts.com/dev/dosemu-import/

**Comment by andrewbird** [comment]
Hi Stuart,
Is this different from the 'unix -s' command we have? Thanks.
~~~
C:\>unix /?
Usage: UNIX [FLAG COMMAND]
 
UNIX -r [ENVVAR]
  Execute the DOS command given in the Linux environment variable "ENVVAR".
  If not given, use the argument to the -E flag of DOSEMU
 
UNIX -c [ENVVAR]
  Execute the DOS program whose Linux path is given in the Linux environment
  variable "ENVVAR". If not given, use the argument to the -E flag of DOSEMU
 
UNIX -e [ENVVAR]
  Invokes "UNIX -c" if the argument appears to refer to a Linux path (ends in
  .com, .exe or .bat, and exists or contains slashes) or "UNIX -r" otherwise.
 
UNIX -s ENVVAR
  Set the DOS environment to the Linux environment variable "ENVVAR".
 
UNIX command [arg1 ...]
  Execute the Linux command with the arguments given.
~~~

**Comment by stuaxo** [comment]
Awesome, looks like no... the only thing it does that could be added to unix -e is an optional second parameter to set the name of the dos envvar to something other than that of the unix one.

**Comment by andrewbird** [comment]
Yes, I think being able to name the variable differently in DOS could be useful, although if environment space wasn't tight one could just copy it, I suppose.

**Comment by stuaxo** [comment]
Seems fairly straightforward to implement 

The only thing I'm not 100% sure of is what the usage string should look like.


Here is a pull request

https://github.com/stsp/dosemu2/pull/70
