### ISSUE TITLE
Minor bug: Error message Neither freedos or comcom32 installation found

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#736]
**Describe the bug**
When booting with other DOS, dosemu2 prints  
```
ERROR: Neither FreeDOS nor comcom32 installation found.
Use DOSEMU2_FREEDOS_DIR env var to specify alternative location.

```
booting process runs well, this error message is not relevant

**To Reproduce**
Boot dosemu with other DOS

![image](https://user-images.githubusercontent.com/7417263/50264695-574af080-044e-11e9-9169-75a49574d07e.png)

**Comment by stsp** [comment]
Yes, it is a bit inconsistent now, as we
do not yet depend on the comcom32 package.
The only way to get this solved, is to help us
getting djgpp into an ubuntu ppa. As soon as
it is there, comcom32 will be installed automatically
so you never see that message.

**Comment by stsp** [comment]
This has nothing to do with FDPP, this is only
comcom32-specific, but freecom also silences
this.
comcom32 is supposed to be dep-requires in
the future. I tend to treat the missing deps as a
hard errors (installation problems).
If I do it your way, you'll boot into "bad or missing
command interpreter" msg quite easily. Its not
the same as missing FDPP, whose absence you
can detect beforehand. Its a primary command.com
and also a fall-back command.com that is loaded if
the one specified in `SHELL=` is not found.
The problem here, really, is that comcom32 is not
a hard dep yet. :(

**Comment by andrewbird** [comment]
> comcom32 is supposed to be dep-requires in
the future.

But why, if we are using FreeDOS we have freecom, if we are using another DOS we have the command.com that came with it?

> If I do it your way, you'll boot into "bad or missing
command interpreter" msg quite easily.

But only if I delete the DOS's command.com from the disk will I see that error, whereas in your scenario I see the other error even when DOS installation is fine. If I understand you correctly in the event that the DOS's command.com is missing dosemu will fix it up by finding the comcom32 instead, not sure that would be expected or desired behaviour, it's too much magic.

**Comment by stsp** [comment]
>>    comcom32 is supposed to be dep-requires in
>>    the future.

> But why, if we are using FreeDOS we have freecom, if we are using another DOS we have the 
> command.com that came with it?

Why what? dep-requires?
Because, as you correctly mentioned, every DOS
comes with its command.com. As such, since we
dep-require fdpp, comcom32 should also be dep-required.

> the other error even when DOS installation is fine.

The error is simply because the initial drive setup
would not be possible. It is being done regardless
of the DOS in use. This was relaxed in 5c1413034,
but after c598f0c53 and 021cdfc46 I am going to
return the unconditional install back.

**Comment by andrewbird** [comment]
> Because, as you correctly mentioned, every DOS
comes with its command.com. As such, since we
dep-require fdpp, comcom32 should also be dep-required.

I thought FDPP was an optional plugin, it's not installed on my Ubuntu system and the PPA packaged Dosemu2 is installed without any missing dependency and runs? If I don't install FDPP, why do I need comcom32 or its missing error message? It seems to me that FDPP requires freecom or comcom32. Why isn't the hard dependency for either of those from FDPP rather than Dosemu2?

> I am going to
return the unconditional install back

Really?!

**Comment by stsp** [comment]
> I thought FDPP was an optional plugin

Currently it is, and if you build dosemu2 from
sources, this will remain so. But for deb/rpm I
am going to hard-dep it. It is absolutely necessary
for distros shipping dosemu2, to have it bootable
out of box. Users who don't need it, may opt it out.

> Really?!

Yes, but you can keep using --Fdrive_c to escape it.
For users of --Fdrive_c nothing practical will change.

**Comment by stsp** [comment]
I can in theory silence this msg if
fdpp support is not compiled. Obviously
no one would care about comcom32
in absence of fdpp.
But this msg, at least for now, is
also about freedos/freecom. If we
silence it depending on fdpp, then
we should also remove a freedos
part of it. I'd probably better delay
this until the removal of dosemu-freedos
support, which is not yet (but will
most likely happen sometime).

**Comment by stsp** [comment]
fdpp should not hard dep on any
command.com, its just a library.
It can be used with any command.com.
Of course you are right that dosemu
should not dep on comcom32 in
absence of fdpp. But this msg is also
about freecom and freedos tools,
which is quite bad.
So if you want, lets disable it when
no fdpp. Later we can strip it to only
mention command.com, whichever
it be to the date.

**Comment by andrewbird** [comment]
I install dosemu from ppa, and also always build locally with fdpp, so it would make no difference for me. From my POV it's not worth your effort, but thanks.

**Comment by stsp** [comment]
This is an intermediate thing anyway.
When we have comcom32 in ppa, it
will get a separate env var, separate
msg and all that. We'll then reconsider
this problem for sure. Lets get djgpp
to ppa. :)

**Comment by stsp** [comment]
"drives" should no longer be created when "not doing install".

**Comment by stsp** [comment]
Should now be fixed.
So for the first time there are no dependency problems
any more. You can DL the packages, and they just work.
This is a number-1 goal of dosemu2.
Something to celebrate for sure. :)
