### ISSUE TITLE
debian/control build-depends on fdpp--not in Debian

### ISSUE THREAD

**Issue by RossBoylan** [stsp/dosemu2#753]
debian/control's last Build-Depends is fdpp.
According  to packages.debian.org, there is no such package in any version of Debian.
apt-file search fdpp, which looks for individual file names, turns up nothing on my stretch system.

**Comment by stsp** [comment]
dosemu2 is oriented on fedora and ubuntu -
just because this is what its developers have.
There are also enthusiasts from other distros
(like arch) who create the packages on their own.
It would be nice if someone familiar with debian
can do that too.
On ubuntu the things are simple: we add fdpp
to PPA. What solution is there on debian?
Can you use fdpp from ubuntu PPA?
https://code.launchpad.net/~dosemu2/+archive/ubuntu/ppa

**Comment by RossBoylan** [comment]
https://wiki.debian.org/CreatePackageFromPPA gives a somewhat involved recipe for using a PPA.
I suspect there are alternatives.
I'm guessing fdpp is https://github.com/stsp/fdpp; it might be just as easy to build a Debian package from there.
Some clue in the readme or INSTALL about this would be helpful.

**Comment by stsp** [comment]
`make deb` :)

**Comment by stsp** [comment]
Or do you mean a dosemu2's INSTALL?
Yes, indeed, that should be updated.

**Comment by RossBoylan** [comment]
Yes, I meant the INSTALL file.

**Comment by stsp** [comment]
OK, I thought you meant the INSTALL file
of fdpp itself, so to build the deb with `make deb`.
I'll update the dosemu2's one.
I wonder if debian has the launchpad
alternative, that can automatically fetch from github
every day, build, put the package to PPA.
https://unix.stackexchange.com/questions/30862/launchpad-equivalent-for-debian
google points here, and it seems there is none.
So I suppose someone should be doing this by
hands.
