### ISSUE TITLE
problems with --Flibdir

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#80]
It would be good to have DOSEMUPREFIX, that works the same as WINEPREFIX - set it to an alternate directory for ~/.dosemu

e.g.

$ DOSEMUPREFIX=~/.dosemudev dosemu

Advantages include: - familiar syntax for wine users
Setup dosemu seperate configs for development, individual apps/games etc.

**Comment by stsp** [comment]
But there is already a DOSEMU_LIB_DIR.
I admit the name is a bit confusing, and I doubt
I've ever used it myself.
Also try --Flibdir

**Comment by stuaxo** [comment]
I'll have a play, not sure they work quite as I'd expect, I tried copying .dosemu to .dosemu2 and seeing if I could get dosemu to use it

```bash
cp -Rp ~/.dosemu ~/.dosemu-other
ln -sfn ~/.dosemu-other/drive_c ~/.dosemu-other/drives/c
echo -e "cls\necho 1st dosemu conf" >> ~/.dosemu/drive_c/autoexec.bat
echo -e "cls\necho 2nd dosemu conf" >> ~/.dosemu-other/drive_c/autoexec.bat
```



Normal dosemu output is as expected:
```
$ dosemu -dumb
[snipped]
1st dosemu conf
```

--Flibdir seems to do something a bit different ?
```
$ dosemu -dumb --Flibdir ~/.dosemu-other/
[snipped]

Sorry, there is no operating system here:
/home/stu/.dosemu/drives/c

Please try to install FreeDOS from dosemu-freedos-*-bin.tgz

Press any key to return to Linux...
```
side note - is the path displayed in the error message here, really the one it was looking in ??


envvar doesn't seem to do anything
```
$ DOSEMU_LIB_DIR=~/.dosemu-other/ dosemu -dumb
[snipped]
1st dosemu conf
```

**Comment by stsp** [comment]
> side note - is the path displayed in the error message here, really the one it was looking in ??

Should be at least one of the places.
It also looks for kernel.sys in $libdir/drive_z as a fall-back.

Would you mind taking a look into libdir problems yourself?

**Comment by stuaxo** [comment]
I'll have a bit more of a dig into it, yep

**Comment by stsp** [comment]
It seems --Fimagedir or --Flibdir are in effect
only when the default path specified in $_hdimage
does not exist (like /home/stu/.dosemu/drives/c).
This is coded so in global.conf, and I hate global.conf. :)
This is a very unlikely condition as dosemu creates
that dir on startup, so these options do not work
almost always.
As such, this is a bug.

**Comment by andrewbird** [comment]
Just quick note: I use --Fimagedir so that I can run dosemu for testing from within the development tree e.g.
~~~
bin/dosemu.bin -n -f test-imagedir/dosemu.conf --Fimagedir test-imagedir/
~~~
and my test-imagedir/dosemu.conf contains just 
~~~
$_lpt1 = ""
$_vbootfloppy = "drives/c"
~~~
where in the test-image subdirectory I create drives/c to hold the test files. If there is a bug, can you ensure that this current behaviour is maintained?

I have never needed --Flibdir, I had always assumed it was the location install would look to find freedos for copying if no valid bootable hdimage was found.

**Comment by stsp** [comment]
> If there is a bug, can you ensure that this current behaviour is maintained?

Or you can fix it yourself instead. :)
If you look at how these vars are handled in global.conf,
you'll see that it first searches in home dir, then in hdimage
dir, then in libdir.

> I have never needed --Flibdir, I had always assumed it was the location install
> would look to find freedos for copying if no valid bootable hdimage was found.

It would be good if it does so, but in dosemu-1.0 the drives
were somewhere in /var/lib/dosemu, so the libdir is still used
as a fall-back.
You are welcome to clean the things up!

**Comment by stsp** [comment]
@andrewbird So if you like to deal with this, let me know
and I won't schedule this to myself. AFAICS this
is just about some global.conf shuffling.

**Comment by andrewbird** [comment]
Yes, assign it to me. It'll make a change from creating boot.blks for my test suite!

**Comment by stsp** [comment]
> Yes, assign it to me.

If you mean github-wise, then sorry, I can't. :)
github doesn't give any flexible control of permissions
on free accounts. It allows either a full access to the
project, or none. None means no way to even assign
the tasks to the person. Some googling reveals that it
is possible for corporate accounts (presumably payed) -
there you can control permissions for different people,
add people to assignees list, etc etc.
I really need to study the FSF's statement on why they
do consider github inappropriate for free projects...

**Comment by andrewbird** [comment]
Oh, I didn't realise that, no worries. BTW the concerns over Github at [Gnu](https://www.gnu.org/software/repo-criteria-evaluation.html) seem pretty trivial. I do appreciate the service offered by Github isn't plastered with adverts and tracking. Conversely, Sourceforge is awful if you run with EFF's Privacy Badger enabled, it doesn't even load the css!

**Comment by andrewbird** [comment]
I did some digging, and have written a few clean up patches so far. But I have some thoughts and could use some input?

1. LIBDIR
  a) Purpose is for keymaps and pristine install of freedos
  b) Defaults to whatever set during ./configure --dosemudir
  c) Can be overridden by --Flibdir
  d) I will remove fallback to /var/lib/dosemu (now in global.conf)
  e) I will make config parsing abort if doesn't exist 
                                                                                
2. HDIMAGEDIR
  a) Current purpose is global fallback if ~/.dosemu/drives missing
  b) Default to whatever is set during ./configure -with-syshdimagedir
  c) Can be overridden by --Fimagedir
  d) Not sure if the existing purpose is valid? I do use it myself for the test suite, but I have no .dosemu/drives and if I did it would never get used.
                                                                                
3. ~/.dosemu/
  a) Purpose is for user data
  b) If ~/.dosemu/drives/* exist they are used in preference to HDIMAGEDIR
  c) install_dos() will use this as a target to install freedos if DOS missing
  d) There is code to allow global.conf to live in ~/.dosemu/lib currently - I'll remove this
  e) No option to alter this location at present, either at compile or run time

BTW the message below that was seen with seemingly the wrong path when --Flibdir was used is okay
~~~
$ dosemu -dumb --Flibdir ~/.dosemu-other/
[snipped]

Sorry, there is no operating system here:
/home/stu/.dosemu/drives/c

Please try to install FreeDOS from dosemu-freedos-*-bin.tgz

Press any key to return to Linux...
~~~
Linux does look in LIBDIR for a pristine copy of freedos to install, but doesn't find one and tries the boot anyway. The message is output by DOS and is in the default boot block shown when no OS is found.

## Questions
- So it would seem that  @stuaxo is looking for a way to control ~/.dosemu; neither LIBDIR nor HDIMAGEDIR will do that, but should we just be allowing a different user image directory, or the whole thing? Remember that there's a logfile, midi and debugger pipes etc. 
- Should the control for dosemu's user data directory be an environment var like DOSEMUPREFIX=~/.dosemudev as @stuaxo suggested, or a --Fuserdir argument to be consistent with the others. My preference is the argument, I don't like magic env vars.
- Install_dos() function makes a drive called ~/.dosemu/drive_c whereas traditionally the directory would be ~/.dosemu/drives/c is that intentional?

**Comment by stsp** [comment]
> d) I will remove fallback to /var/lib/dosemu (now in global.conf)

I don't think this is needed. The fall-back doesn't
hurt, and some dosemu-1.x users will definitely complain.

> d) Not sure if the existing purpose is valid?

That's a pure bug IMHO.
Please note that these vars are not to be set by
the user. This is very important to understand.
They are instead set by the parser for global.conf's
use. Users should never mess with that, and as the
result, we should not even discuss the var: we should
discuss the use of --Fxxx and forget what vars do they
internally use. If it was ever possible to alter the vars
directly (not sure), it should be disallowed.

> b) If ~/.dosemu/drives/* exist they are used in preference to HDIMAGEDIR

Which says nothing useful. The more interesting fact
is that then it also takes the preference over --Fimagedir.

> e) No option to alter this location at present, either at compile or run time

Just speculating: I think Bart was very desperate to find
some fixed per-user location for the disclaimer file. :)

> The message is output by DOS and is in the default boot block shown when no OS is found.

You probably miss the fact that --Flibdir can be used as
a fallback for the hdimage dir. So if it is specified, I would
expect it should try booting from there too. And I am pretty
sure if you used --Fimagedir instead, you'd get the same
error msg.

> a different user image directory, or the whole thing? Remember that there's a logfile,
> midi and debugger pipes etc. 

Lets start from the simple solutions and bug fixes.
Which would mean lets make the image dir working
first, then see.

> My preference is the argument, I don't like magic env vars.

They are not for the user, and I hope they are not documented
as such, too. So I think there is no such question, but if they are
documented, the things are more difficult.

> Install_dos() function makes a drive called ~/.dosemu/drive_c whereas
> traditionally the directory would be ~/.dosemu/drives/c is that intentional?

I think that layout was taken from wine, and it
probably makes sense. Dosemu should have the place
for symlinks to different things: to r/o global dirs for
commends, and to empty storages for user data.
So it creates the drive_c as the storage, and makes
a symlink to it. Then it creates the symlinks to other
things. We could as well create a completely empty
drive_h for user data for example, and tell the user
that C: is a system drive and should not be used for
the data (this is just the example, of course). If we
create such drive_h somewhere, we'll also have to
put a symlink to it. Also dosemu2 honours EXTRA_DOSDRIVE
var which you can also point to some storage dir
like drive_i. So I think having an extra dir is not a
problem if it makes things more logical.

**Comment by bolle732** [comment]
For my self, I have everything in a single program directory. During DOSEmu 1.x time, I've patched my compiled DOSEmu to not look for or create any .dosemu directory (and even removed the install routines...).

One reason has been, that I have i.e. a server running, where users can instantiate a DOSEmu instance over a website and access them by VNC. There can be multiple DOSEmu instances running at one time under the same Linux user account. I build the configuration on the fly for each instance. Having everything in ~/.dosemu would clash here.

I do not care much about the defaults, as long I can easily overwrite them.

Some mechanisms for relative paths used i.e. for $_hdimage and $_lptX would be nice.

From my point of view, it would be nice if one can pack a DOS program with the needed DOS system files and configuration into an archive. This archive could be distributed and the user can simply extract its content into a directory of his choice. With the archive, a start script could be provided which runs the program with DOSEmu. No dependencies to the system wide installed FreeDOS.

@stsp : I still haven't changed the way I use the config.sys / autoexec.bat. I will if I have time for that...

**Comment by stsp** [comment]
> Having everything in ~/.dosemu would clash here.

I don't think so. If you find such a behaviour, please report a bug.
We never prohibited the users from running multiple dosemu
sessions.

> Some mechanisms for relative paths used i.e. for $_hdimage

Isn't it already there?

> From my point of view, it would be nice if one can pack a DOS program with the
>  needed DOS system files and configuration into an archive

Yes, that would be great. If I am to implement that,
I'd use the archivemount prog to temporary mount
the archive to some tmp dir and point dosemu there.

**Comment by bolle732** [comment]
The last time I've tried relative paths, it didn't worked. Have to try again.

For example Commander Keen or Wacky Wheels ? If they are free, could we have them here on GIT as a reference for tests ?

**Comment by bolle732** [comment]
Regarding multiple instances, what would happen to the boot.log file ? Does each instance create one with different names ?

**Comment by stsp** [comment]
> The last time I've tried relative paths, it didn't worked. Have to try again.

Ah. The whole point of this ticket is to get
them to work. So don't try yet. :)

> For example Commander Keen or Wacky Wheels ? If they are free, could
> we have them here on GIT as a reference for tests ?

For test of what?

> Regarding multiple instances, what would happen to the boot.log file ?
> Does each instance create one with different names ?

If you use "dosemu" script instead of dosemu.bin then
yes. And you can alter the log file location with -o. And
if even this is not enough, you can just don't care about
the log - it is only needed for bug reports.

**Comment by andrewbird** [comment]
I think I didn't make my terminology clear: When I say LIBDIR, I'm talking about the value set by --Flibdir or the compiled in default from ./configure --dosemudir, not the tokens or vars used in parsing global.conf / dosemu.conf. A similar thing is so of HDIMAGEDIR i.e. --Fimagedir  && ./configure --syshdimagedir.

As I understand it, global.conf *only* sets HDIMAGEDIR to LIBDIR if the HDIMAGEDIR is not set or doesn't exist. The not set issue only occurs in very old dosemus and since we use the compiled in global.conf I don't see how that fallback could ever be used. If the directory specified at configure time by --syshdimagedir doesn't exist, then that's an installation or packaging problem. There has to be some end to the discovery logic somewhere, don't you agree?

A goal I have set myself in doing this is that I would like to simplify global.conf wherever possible; having hard coded path defaults within does not seem to fulfil that goal.

For now, I pushed a branch https://github.com/andrewbird/dosemu2/tree/dirs-01 to show my current thoughts, but no PR yet. Fundamentally nothing has changed yet apart from the clean ups I mentioned.

I think that there is no bug with current devel behaviour, only unexpected fall backs and unimplemented features.
I think it's correct that:
- --Flibdir value overrides ./configure --dosemudir value
- directory specified for above is used as the freedos source for installation of DOS missing
- directory specified for above is used as the base for the keymap/ location
- --Fimagedir value overrides ./configure --syshdimagedir value
- that ~/.dosemu/drives/* are found in preference to directory above

I would like to add a '--Fdrivedir' that would be used instead of ~/.dosemu/ and be prepended to the value of $_hdimage / $_vbootfloppy etc. That way different drive setups are possible for a single user, but logfile, disclaimer and pipes still reside where they are expected.

**Comment by stsp** [comment]
> --syshdimagedir doesn't exist, then that's an installation or packaging problem.

I don't think we still need or use --syshdimagedir.
Perhaps it should be removed. In which case the fallback to
libdir may still be good.

> I think that there is no bug with current devel behaviour, only unexpected fall backs

I think that depends on whether the default hdimage
path existed for @stuaxo or not. If it existed but missed
boot files, then you are right. However, in that case the
--Fimagedir have to be tried, and if it causes the similar
failure, then this is certainly a bug. If the hdimage path
didn't exist and the --Flibdir was specified, then again,
what we see is a bug.

> --Fimagedir value overrides ./configure --syshdimagedir value

Perhaps better to remove --syshdimagedir.

> that ~/.dosemu/drives/* are found in preference to directory above

No.

> I would like to add a '--Fdrivedir' that would be used instead of ~/.dosemu/ and be prepended to the

Also likely no, this just adds a complexity for nothing.
You'll have to define the rules how this overrides --Fimagedir etc.
While instead you could do simply
--Fimagedir=$DRIVE_PREFIX/some_dir - more flexible than
anyone can think of.

**Comment by andrewbird** [comment]
So if understand correctly, you want to repurpose the --Fimagedir option?
- Remove Imagedir's default value (currently set via ./configure --syshdimagedir)
- if --Fimagedir is not specified drive lookup is first in ~/.dosemu, then libdir
- if --Fimagedir is specified then drive lookup in ~/.dosemu & libdir is not done, only imagedir is checked

If my understanding is correct, that would be the **best** solution for my test suite. I think it would also fit with the @stuaxo desire to have separate directories for certain applications. If he combined it with -n and -f he could have separate configs there too.

Regarding my [dirs-01](https://github.com/andrewbird/dosemu2/tree/dirs-01) branch are there any commits you particularly don't like? I'll be working on another branch for a PR anyway, but it's good to know :-)

**Comment by stsp** [comment]
> So if understand correctly, you want to repurpose the --Fimagedir option?

What you describe below is correct: that's how I
see the --Fimagedir use. But I am not sure about
"repurpose": I think we don't use /var/lib/dosemu
for very long, so the current purpose seems missing.
To me its more like fixing the left-overs that previous
devs haven't spotted while transferring things to the
per-user locations. _They_ had to repurpose it, but
forgot, and as the result it doesn't work. We just clean
things up for them.

> Regarding my dirs-01 branch are there any commits you particularly don't like?

3f8185d4 for instance. Why would you need to remove
the fallback to /var/lib/dosemu?
Also I wonder what to do with 22704828. Looks reasonable,
but the question is still why not can the user have some
private freedos copy from which he wants to try an installation?
Then private libdir can be in use.

**Comment by stsp** [comment]
Also if you do such PR, I may opt to delay it for the
next pre. We have already too many things accumulated,
and these small clean-ups should be tested well.

**Comment by andrewbird** [comment]
Regarding:
- 3f8185d, if we are killing off ./configure --syshdimage then I'm happy for it to stay.
- 2270482, also happy for it to stay if there's a need.

**Comment by stsp** [comment]
> also happy for it to stay if there's a need.

I am actually not sure.
I think there is a need, but it can be coded in a
"dosemu" wrapper script, so that it just sets the
--Flibdir to the user-private location. So maybe
I'd like to see such a replacement, or maybe I am
fine with your current patch that doesn't provide
any replacement. Lets say it is up to you: if you
think the replacement is not needed or difficult
to code, then I can apply the patch as is.

**Comment by stuaxo** [comment]
It's great that the commandline can override conf/globals/defaults for --Fimagedir with this patch, would it make sense for that to the default for all settings ?

**Comment by stsp** [comment]
> It's great that the commandline can override conf/globals/defaults for --Fimagedir with this patch

Unless I am missing something, the patch does not yet do this.

> make sense for that to the default for all settings ?

If you find any other that misbehave, then yes.

**Comment by andrewbird** [comment]
@stuaxo the patchset doesn't really change anything yet. --Fimagedir existed before and will do as you might expect, except if you have ~/.dosemu/drives/* in which case they get used in preference. A future patchset aims to make --Fimagedir authoritive in that case.

**Comment by bolle732** [comment]
I've retested relative paths and with '--Fimagedir' I can use them with and without a leading './'. That's really nice. If I could use '~/' for referring the home, then it would be perfect ;-) One configuration which would work on all my machines...

**Comment by stsp** [comment]
You can use $HOME instead of ~/

**Comment by bolle732** [comment]
I tried '$HOME' before, but it doesn't work in my case.

Using:
```$_hdimage = "./drive_c $HOME/Documents /media"```

would give me a "C:" on "drive_c" and a "D:" on "/media".

**Comment by stsp** [comment]
Hmm, you were just yet talking about '--Fimagedir',
not $_hdimage.

**Comment by bolle732** [comment]
Ok, then I missed to make it clear. Sorry.

I tried '--Fimagedir' because I want a single 'dosemurc' for use on different systems. But on this systems, I have different user names. And one of them is integrated into an Active Directory...

I have the following home paths:
/home/<userA>
/home/<userB>
/home/<domain>/<userC>

Therefore, it would be nice to have the parser of 'dosemurc' supporting environment variables or at least the expansion of '~/'.

**Comment by stsp** [comment]
I don't understand what are you talking about.
All you need is to put symlinks to ~/.dosemu/drives
for every user. In the example above, you should
just have ~./dosemu/drives/d --> $HOME/Documents

**Comment by stsp** [comment]
You can also use DOSDRIVE_EXTRA=$HOME/Documents

**Comment by stsp** [comment]
@andrewbird maybe --Fimagedir should also allow
multiple pathes? Otherwise the way it overrides
$_hdimage is not adequate. I think this is the reason
@bolle732 asks for env vars in $_hdimage: one can
use the env var with --Fimagedir but then it can't add
multiple dirs...

**Comment by stsp** [comment]
Env vars in $_hdimage are now supported.

**Comment by stsp** [comment]
> I'm not keen on globbing in the global.conf as it prevents fixing #80 in a sensible manner.
> There I would like to do imagedir path resolution in C and use at common function for floppy
> and hdimage.

I wouldn't be against globbing in C, if you like.
I guess you can do that with glob()/wordexp() funcs.
Having global.conf reduced and eventually removed
would be an interesting but a very difficult goal.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by andrewbird** [comment]
Great that you removed the syshdimage stuff. I noticed a change, which I believe is correct, but might trip others up if trying to run without installing, is that the libdir must now exist.
~~~
CONF aborted with: DOSEMU_LIB_DIR does not exist /usr/local/share/dosemu
~~~

I work around this by overriding it on the command line
~~~
mkdir test-libdir
env FDPP_KERNEL_DIR=test-imagedir/dXXXXs/c bin/dosemu.bin \
      -n -f test-imagedir/dosemu.conf -D+dRWD -o test.log \
      --Flibdir test-libdir --Fimagedir test-imagedir
~~~

**Comment by andrewbird** [comment]
Oh you might also like to rename the remaining variables that have 'hdimage' in their name to 'image' and defines that are HDIMAGE to IMAGE etc, which would hopefully would finally clear up the confusion with the now removed syshdimage stuff.

**Comment by stsp** [comment]
I think libdir should point to the location
of plugin libs. Keymaps can be put there
as well.

**Comment by stsp** [comment]
Whats the use of renaming?
Would you like to create the patch? :)

**Comment by andrewbird** [comment]
> I think libdir should point to the location
of plugin libs. Keymaps can be put there
as well.

I guess so, but even with my --Flibdir pointing at an empty directory things seem to work okay, except for a whinge about commands and installation sources.
~~~
ERROR: No system files found at /common/src2/dosemu2.git/test-libdir/fdboot
ERROR: dosemu2 commands not found at /common/src2/dosemu2.git/test-libdir/dosemu2-cmds-0.2
~~~



> Whats the use of renaming?

Purely cosmetic, option to override is called --Fimagedir and it's where all the drives live not just 'hd' ones.

> Would you like to create the patch? :)

Sure, if you like, but it's trivial I think.

**Comment by stsp** [comment]
> I guess so, but even with my --Flibdir pointing at an empty directory things seem to work okay

Yes, because at that point --Flibdir is mostly unused.
Maybe we should just remove it?
Redefining the location of plugins, or the
search pathes of fdpp etc - why do we need
that to ever be redefined?

**Comment by andrewbird** [comment]
I guess `--Flibdir` might be useful if someone wanted to develop an out of tree plugin, otherwise the plugins pretty much need to match the dosemu.bin binary and hence location can be compiled in if absolute, or discovered relative to dosemu.bin location. For me you can remove `--Flibdir`, but perhaps someone else has an excellent use for it?

**Comment by stsp** [comment]
> someone else has an excellent use for it?

If only "had".
It didn't cover the plugins location even in the
past. That was just an idea. But... I'd say this
idea can wait until someone really decide to
develop a custom plugin, and not to upstream
it...
