### ISSUE TITLE
Question: DOS FAT filesystem benchmark tool?

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#815]
For fun I've written a block device driver that uses dosemu host memory to provide a 128Mb ramdisk for DOS. I want to benchmark it to see if there's any significant advantage in speed over EMS / XMS DOS based ones. Does anyone know of a FAT filesystem speed test tool that runs under DOS, note it must use MSDOS int21 functions not BIOS like int13 etc?

Just in case anyone feels like playing with it :smile:
https://github.com/andrewbird/dosemu2/tree/emudsk01-sys

**Comment by stsp** [comment]
I am sure its faster than EMS or XMS.
Why to even bench-mark it, it avoids the nasty
copies from 1Mb zone, so its pretty obvious.
What I also am sure in is that you can simply
lredir to tmpfs. In which case it will also be visible
from the host.
What's the deal?

**Comment by andrewbird** [comment]
It was just a little experiment for a challenge :smile:, probably no real use for anyone because as you say you can lredir.
#### In my first iteration I had it:
- loading as a TSR
- inserting itself as a device driver into the device driver chain
- creating a DPB, inserting into the DPB list
- finally adding it into a CDS entry at an arbitrary drive letter

#### The downside with the TSR is that it:
- Required knowledge of DPB, device driver and CDS structures, which no user program should do.
- Wasted memory for TSR's PSP and left memory fragmented where its env block was freed. Actually that's probably a good reason to convert the fossil TSR to a proper device driver.

So the previous three commits are probably worth having (display device driver chain / display DPB list in dosdebug, and a typo), so I'll rebase them against current.

**Comment by andrewbird** [comment]
I'd still like to benchmark the driver, for personal satisfaction, if anyone has an idea for a tool to use?

**Comment by ecm-pushbx** [comment]
> * Required knowledge of DPB, device driver and CDS structures, which no user program should do.

Redirectors do need to know the CDS structure too. And I think linking in an MS-DOS 6.xx compatible DPB is sufficient for MS-DOS 7.10 (with FAT32 support), if the drive in question is always formatted with FAT12 or FAT16 (not FAT32). The device driver structure has been very constant since MS-DOS 2.00.

> * Wasted memory for TSR's PSP and left memory fragmented where its env block was freed. Actually that's probably a good reason to convert the fossil TSR to a proper device driver.

Another wasted resource is file handles. Especially if you do "> NUL" for a command that installs as a TSR, the SFT pointing to NUL will be leaked effectively. (The default CON, AUX, and PRN handles will usually be duplicated from the parent's process handles to these SFTs, so the SFT is just referenced more than needed, not leaked entirely.)

To remedy some of that, besides freeing the environment block (as you already imply), you can also close all files before Int21.31. Also, you can relocate the PSP to insure it doesn't fragment memory. In my own TSR example, I do not use a 21.31 call but rather (after PSP relocation to the top of the LMA) I allocate a block of memory for the resident portion of the program, without a PSP, then hack the MCB to make it self-owned (and no longer owned by the program's PSP). Then I exit with 21.4C, which closes all files and deallocates memory other than the resident self-owned block.

My example is available at https://bitbucket.org/ecm/rxansi/

**Comment by andrewbird** [comment]
> Redirectors do need to know the CDS structure too.

   Yes you are quite right, I spent some time a while ago removing most CDS access from outside the MFS redirector code in Dosemu. I found it a little ironic that I found myself wanting to manipulate it from my latest experiment, and hence the reason I reverted to a proper device driver where DOS would do all the grubby work with DPB and CDS. My only motivation for using the TSR was that I could create the ramdisk with an arbitrary drive letter, whereas the device driver allocates the next one available.
   I had considered installing the block device driver with no units to avoid the fragmentation issue, but to DOS that's a failure condition and it unloads it. One thought I did have was to install as a character driver, later when creating the drive flip the header bit to make it a block device, and do the DPB creation/insertion and CDS manipulation. I'm pretty sure that would work, but it suffers from the same CDS/DPB access issues as the TSR that I'm so uncomfortable with.

> Also, you can relocate the PSP to insure it doesn't fragment memory. In my own TSR example, I do not use a 21.31 call but rather (after PSP relocation to the top of the LMA) I allocate a block of memory for the resident portion of the program, without a PSP, then hack the MCB to make it self-owned (and no longer owned by the program's PSP). Then I exit with 21.4C, which closes all files and deallocates memory other than the resident self-owned block.

That's an interesting proposition for fossil.com, I think. One thought about relocating the PSP from the running program, does DOS not keep track of where it is for termination purposes?

**Comment by ecm-pushbx** [comment]
> That's an interesting proposition for fossil.com, I think. One thought about relocating the PSP from the running program, does DOS not keep track of where it is for termination purposes?

You can read the implementation in RxANSI's install function, at https://bitbucket.org/ecm/rxansi/src/0c2ae4e04ef4676a8ce1ddd68e8bff1f96f9f147/RxANSIT.ASM#lines-791

* At line 808 it resets the environment segment field in the PSP, then
* at 811 frees the environment block explicitly.
* At 821 it shrinks the PSP's / program memory block.
* At 826 it sets up the LMA-only, last fit UMB link and memory strategy.
* At 834 it allocates memory for the relocated program.
* 847 copies the data from the original program memory to the relocation target block.
* 849 makes the relocation target block self-owned.
* 853 actually relocates the running code to the new segment.
* At 877 the PHT (up to 20 entries) is copied into the new about-to-be PSP.
* At 882 the entries copied are cleared in the original PSP.
* At 885 the old PSP's Int22, Int23, and Int24 fields are modified to reflect the program's own handlers (instead of the original parent's).
* At 891 the original PSP's parent field is set to point to the target PSP.
* Then at 905 we terminate the original PSP with 21.4C, freeing all memory still allocated to the original PSP, and closing all additional files if the PHT was larger than 20 entries.

I determined that this dance should be the most reliable way to relocate a PSP.

**Comment by ecm-pushbx** [comment]
> One thought I did have was to install as a character driver, later when creating the drive flip the header bit to make it a block device, and do the DPB creation/insertion and CDS manipulation. I'm pretty sure that would work, but it suffers from the same CDS/DPB access issues as the TSR that I'm so uncomfortable with.

Right. You could also install a device driver with how ever many units you desire, and keep them "uninitialised" so to say. DOS would allocate a DPB and CDS entry for each unit you specify to it, but you could fail all accesses until a later point in time.

BTW, you can make an executable that executes either as a device driver in CONFIG.SYS, or as a regular program. To do that, you can create a .COM executable with a short (or even near) jump in the device driver header's "next" field (the first data item in the image), which for example our DRVEXCH does (quoting from the source code available at http://www.bttr-software.de/products/drvexch/ under GNU GPL v2+):

```
  section .text

  org 0  ; it is a device driver

; device driver header
devdrvrhdr
  jmp short runcom      ; will be patched to -1 later
  dw -1                 ; pointer to next device driver header
  dw 1000000000000000b  ; device driver attributes (character device driver)
  dw stratfunc          ; offset to device driver strategy routine
  dw intfunc            ; offset to device driver interrupt routine
  db "DRVEXCH$"         ; device driver name

; when loaded as COM, control is passed here
runcom:
  xor cx, cx
  push cs                         ; retf will restore cs = PSP and jump to
  push cx                         ; PSP:0 (int 20h, terminate program)
  mov byte [0ffh], 0dh            ; cut command line against Borland IDE bug
  mov bp, [2]                     ; first unavailable paragraph above program
  mov ax, cs
  mov word [paramptr + 102h], ax
  sub ax, -16                     ; segment fixup, cf = 1
  mov si, .segjmp                 ; (COM program would have "org 256")
  push ax
  push si
  retf                            ; jmp far .segjmp
.segjmp:
  call main                       ; main procedure, with cx = 0, cf = 1
  retf                            ; terminate
```

As noted, the device driver header next (offset) field is initialised to -1 by the device driver entrypoint. DOS checks that **after** calling the driver's entrypoints for initialisation, and takes non -1 offsets as indicating the next device driver header's offset (the segment is assumed as the same). You can look at it in the MS-DOS 2.00 source here (under MIT License): https://github.com/Microsoft/MS-DOS/blob/master/v2.0/source/SYSINIT.ASM#L943

The other, simpler way is to use an MZ EXE where the executable image starts with a device driver header, but the normal-program entrypoint is set to some other location than the very start of the executable image. If I recall, Microsoft actually did that in some programs already. (EMM386.EXE ?)

**Comment by andrewbird** [comment]
Thanks for this, lots of interesting stuff to look at in the coming days.

**Comment by andrewbird** [comment]
I found a benchmark tool for DOS [IOStone](http://www.acnc.com/iostone.zip). Comparisons of various dosemu2 filesystems

File system | iostones | seconds
--------------- | -----------| -----------
MFS | 35,700| 70
FAT12(Image File) | 70,000 | 22
EMUDSK | 66,667 | 27

So it looks like an Image file is better than a ramdisk, probably because Linux has it all in memory anyway.

**Comment by stsp** [comment]
Why do you need ssd?
Try tmpfs.

**Comment by stsp** [comment]
For fatfs dosemu only caches FAT table
and a few more, but not files.

**Comment by andrewbird** [comment]
> Why do you need ssd?

No reason, except that's what /tmp seems to be on my system these days not tmpfs

> For fatfs dosemu only caches FAT table and a few more, but not files.

I couldn't test fatfs as it's readonly. I think the FAT image is fast because Linux probably has it all cached in memory at filesystem level after a few accesses.

It shows me that my ramdisk block driver isn't needed, however it's been an interesting experiment for me.

**Comment by stsp** [comment]
> I couldn't test fatfs as it's readonly.

IIRC it pretends to be rw but doesn't store the
results anywhere. :) So maybe you can?
