### ISSUE TITLE
docs and behavior don't match, esp for startup

### ISSUE THREAD

**Issue by RossBoylan** [stsp/dosemu2#822]
The documentation, which I presume is mostly for dosemu without the 2, does not match the current behavior of the program or provide guidance to some aspects of customization.

The introduction of README.html gives layout of of the dos drives that is inconsistent with what I actually have, in which D:, E:, and F: are system drives associated with dosemu, freedos and comcom32.  It says autoexec.bat and config.sys are on c:, which they are not.

Since those files do exist on d:, which is mapped to /usr/share/dosemu/dosemu2-cmds-0.2/, not writable for ordinary users, it is not clear how or where to customize those files.

There are probably a lot more things like that, but that's what has caught my eye.

**Comment by stsp** [comment]
No, this is mostly correct.
You can still put those files on C and
customize them there. You should
ignore their presence on other drives.
So while dosemu2 got some extensions,
most things still follow the documentation.
Of course documenting some dosemu2
additions like userhook.sys might be a
good idea by itself.

**Comment by RossBoylan** [comment]
Are you saying that autoexec.bat, config.sys, and perhaps other config files that appear on other drives inside the emulator are not executed/used at all, or just that if I drop something in c:\ that will replace them for startup purposes?

________________________________________

**Comment by stsp** [comment]
Second. Everything is overridable.
But not config.sys - its now fdppconf.sys.
If you insist on using config.sys on C
as override, you should also override
the boot kernel by putting kernel.sys to C.
And it all will work exactly the way it was
documented.

**Comment by stsp** [comment]
So if you put fdppconf.sys to C, you'll
override. If you put kernel.sys and
config.sys to C, you'll also override.
But putting config.sys alone won't
override. Instead you can create
userhook.sys, and that will be included
into the boot process.

**Comment by stsp** [comment]
Would you like to send the documentation
patch?

**Comment by stsp** [comment]
Found this rather interesting thread:
http://www.vcfed.org/forum/showthread.php?69746-Using-DOSEMU-on-64-bit-Linux-issues/page3
Basically people complain to documentation
and to inability of working with the 1.x configs.
Since the 1.x configs are usually all commented
out by default, its not clear what was the problem
exactly. But the problem with documentation was
exactly as spelled in this ticket: that people do not
know how to customize the start-up files. Even
though all the 1.x ways still work because of
the config file overrides, people don't believe
this is the case and are trying to edit the dosemu2-
specific files, which usually leads to a bad luck.

So does anyone want to write a few lines of
an explanation about the start-up customization?
In fact, I think the very basic and small things
like this can be documented in a wiki, or maybe
in a top-level README.md to be visible on a very
first glance?

**Comment by stsp** [comment]
> though all the 1.x ways still work because of
> the config file overrides, people don't believe

EDIT: no, they don't. At the course of the thread
they discovered the different names (fdppconf.sys/autofdpp.bat),
which is a real show-stopper unless documented.
Hmm... should I allow the old names for overrides,
or better to write docs? :(

**Comment by stsp** [comment]
But OTOH fdppconf.sys/autofdpp.bat are the files
inferred by fdpp, not dosemu2. dosemu2 has nothing
to do with them. So the docs will need to also explain
what fdpp is and how to override also that...
Looks like no simple solution here. :(

**Comment by stsp** [comment]
The lengthy warning is now telling about the
boot process customization.
Let me know if this is not enough.

**Comment by stsp** [comment]
In fact, the short migration guide would be good
to have. Please post the topics here, and maybe
one day...

- my `.dosemu/drives/*` no longer work
- how to customize boot process/my `config.sys` no longer work
- new location of `.dosemurc`
- why scaling filters do not work
- why LFNs do not work (aka `dir /lfn`)

Anything else?

**Comment by stsp** [comment]
Will track that in #994.
