### ISSUE TITLE
alt-enter for fullscreen...?

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#83]
Every virtualisation tool has different keystrokes for fullscreen, including dosemu, and they are all difficult to remember.

We should consider alt-enter as anybody that has fullscreened a dos app in windows has used it already.

**Comment by stsp** [comment]
We can consider a patch making it a config option.

**Comment by stuaxo** [comment]
Heh, I knew this would happen which is why I didn't submit it earlier - will try and look at it around the same time as the other config related ticket.

**Comment by stsp** [comment]
> Heh, I knew this would happen

Yes, quite predictable. :)
You propose the very small extensions that
can be only made optional, because having
them unconditionally will break the experience
of the former dosemu1 users. And making
them configurable is a considerable work.
For such things you need to either send the
patch or the money - you'll find the same with
the other free projects too.
I can only offer the bug fixes (mostly a regression
fixes) for free. That said, I'd probably have to
look into a libdir situation unless you do. :)

**Comment by stuaxo** [comment]
Yep - it makes sense that this would break older users expectations, so should either be configurable or default to both (will see when I get to implementing).

- I'm pretty much just slowly putting up things that have bugged me about dosemu since I first used it in 1998, it's probably too easy on here compared to sourceforge ... but also *much* easier to contribute too.

I'm alternating between this and some other projects, so not going to start on the libdir thing for a little while at least, but will let you know if I do.

**Comment by stsp** [comment]
So feel free to open a pull request.
