### ISSUE TITLE
SDL2 / X  / Mir / Wayland on Linux

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#87]
Raising this issue is more for talking SDL1/2 etc than identifying an actual problem. I noticed before, and I think Stas mentioned it the other day, the SDL plugin has heavy use of the X plugin for some functions such as keyboard etc. In an ideal world the SDL plugin wouldn't need the X one loaded, so I started looking at the code and thinking about how to untangle them. This led me to consider that SDL might not run an X environment at all. SDL1 used to be able to run on the linux framebuffer directly, but SDL2 dropped support for that, so the only current usage for SDL2 is running on X, although Mir & Wayland support is in SDL2. Does that mean we can depend upon X always being around in the SDL2 plugin and drop the X_SUPPORT ifdefs etc?
I notice you have an SDL1 based branch in git, are you planning a new SDL1 plugin specifically to support framebuffer, or is it dead code?

**Comment by stsp** [comment]
> SDL1 used to be able to run on the linux framebuffer directly, but SDL2 dropped support for that

This is not quite correct:
https://github.com/llafuente/radamn/blob/master/deps/SDL2/README.DirectFB
Maybe it is just distros that build SDL2 without a
console support at the moment, but this can change.

> Does that mean we can depend upon X always being around in the SDL2 plugin and drop the 
> X_SUPPORT ifdefs etc?

Currently SDL plugin depends on X plugin even for
the font rendering. But SDL has SDL_ttf rendering engine.
We need to identify the areas where the X code really
gives something above what SDL gives (the candidate
it i18n for example - we probably want to use XKB) and
rewrite the rest in an SDL way.

> I notice you have an SDL1 based branch in git, are you
> planning a new SDL1 plugin specifically to support framebuffer, or is it dead code?

SDL2 still has too many bugs and problems.
But SDL1's console support is also broken because
of this:
https://bugzilla.libsdl.org/show_bug.cgi?id=1715
unless you are root.
I don't know if we need an SDL1 code in.
I resurrected the code and if there is a need, I'll merge.
In ideal world of course it is not going to be needed.

**Comment by andrewbird** [comment]
Yes thanks for the directFB link. It seems that since 2.0.0 it's off by default and my distro(Ubuntu) doesn't enable it at package build time. That being said, they are adding Mir support to the build, which I guess is unsurprising since Mir is their baby.

**Comment by stsp** [comment]
Do they provide directFB? If not - no wonder
its support is disabled.
In fact, if font rendering and screen selection is
untangled, then the things are much better.
Only i18n will remain, and its optional.
But really, if you have some free time, you
can consider solving these bugs:
https://bugzilla.libsdl.org/show_bug.cgi?id=2895
https://bugzilla.libsdl.org/show_bug.cgi?id=2893
With these fixed I'd feel much safer having SDL
by default.

**Comment by andrewbird** [comment]
DirectFB is available, but the libs were not installed by default, so I expect directfb support for libsdl2 is not compiled in, at least on 14.04 LTS Ubuntu. I see your bug reports, but they didn't generate any response yet.

**Comment by stsp** [comment]
Yes, that's why someone on our side have
to work on them. :)
So overall we may leave some X deps, but
most of them should be worked out.
I expect SDL_ttf would be an interesting
experience, so please take it before too late. :)

**Comment by andrewbird** [comment]
I'm just reading the SDL changelog, it seems like they are about to release 2.0.4 soon. Notable commits are:
http://hg.libsdl.org/SDL/rev/8a89b58895c1
http://hg.libsdl.org/SDL/rev/41ce18cb4b3b
http://hg.libsdl.org/SDL/rev/08b2895a935a

**Comment by stsp** [comment]
SDL2 has i18n too, but it is separate from the
keypress events:

"You no longer get character input from SDL_KEYDOWN events. Use SDL_KEYDOWN to treat the keyboard like a 101-button joystick now. Text input comes from somewhere else.
The new event is SDL_TEXTINPUT. This is triggered whenever there's new text entered by the user. Note that this text might be coming from keypresses, or it might be coming from some sort of IME"

So unless you know otherwise, I don't think SDL2's
i18n can be used by dosemu.
