### ISSUE TITLE
MSDOS 8 boots from directory, but not image.

### ISSUE THREAD

**Issue by stuaxo** [stsp/dosemu2#977]
**Describe the bug**
Booting from the MSDOS 8 image file results in "invalid system disk".

Extracting the files with mtools to a folder and booting from that works:
```
mkdir msd800bd
mcopy -i msd800bd.img "::*.*" msd800bd
```

```
# dosemurc
$_floppy_a = "/path/to/msd800bd.img"
$_bootdrive = "a"
```

**To Reproduce**
Run dosemu pointing at the image.

**Attach the binaries or provide an URL**
MSDOS 8.0 bootdisk from here
http://www.manmrk.net/tutorials/bootdisk/index.htm

**Attach the log**
https://gist.github.com/stuaxo/31abac332de5fc687cfb00ee73d5abb0

This is with the example flags of everything except video

**Comment by andrewbird** [comment]
I didn't check as I'm away from home at the moment, but is that bootdisk made the same way as you described yesterday by extracting from a DLL? Perhaps it has not had the boot block installed correctly. Since copying the files off to a directory successfully boots under Dosemu's 32bit loader, it would seem that for the image either missing / incorrect boot block, or file placement of IO.SYS would be the issue.

**Comment by stsp** [comment]
These are bad images of msdos8.
See the nearby ticket where I
provided the url to good one.

**Comment by stuaxo** [comment]
Thanks for your patience, it seems like anyone and their dog makes "distros" of later DOSes (including MS themselves) :)
