### ISSUE TITLE
freedos: Error in the DJ mechanism!

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#992]
**Describe the bug**
Latest freedos build produces lots of such errors.
Not sure what does that mean.

**To Reproduce**
Just boot.

**Attach the binaries or provide an URL**
[kernel.sys.gz](https://github.com/stsp/dosemu2/files/4106367/kernel.sys.gz)

**Comment by andrewbird** [comment]
Did you use the repo at https://github.com/FDOS/kernel ?

**Comment by stsp** [comment]
I use https://github.com/PerditionC/fdkernel/
But I had to undo the patches they did in an
attempt to re-sync with fdpp as they are both
wrong and break build.

**Comment by stsp** [comment]
Note that freedos boots.
These errors are not fatal.
But for an extra care it would
be good to check what's going on.

**Comment by andrewbird** [comment]
When I reported the PerditionC one as broken for build, I was told to use the FDOS as primary from now on. I'm not sure of the former one's status anymore.

**Comment by stsp** [comment]
Marvellous!
Builds and no error msg.
And no fdpp patches.
I think the PerditionC branch
have died after an unsuccessful
fdpp sync attempt. :)

**Comment by stsp** [comment]
Just in case you want to try it:
[kernel.sys.gz](https://github.com/stsp/dosemu2/files/4106473/kernel.sys.gz)

**Comment by andrewbird** [comment]
Cool, boots without error for me too!

**Comment by bartoldeman** [comment]
FDOS has been the primary for quite a while (almost two years), it says so in the description of the PerditionC branch too. I was surprised to see the PerditionC branch being updated too independently but Kenneth's been merging at times.

**Comment by stsp** [comment]
At least fdpp was forked from PerditionC branch, as
I didn't know this shouldn't be done. Not sure what
are the consequences of that now, though.

**Comment by bartoldeman** [comment]
they were probably almost identical when you forked it (if the FDOS even existed already) so not a big deal I gather.

**Comment by andrewbird** [comment]
I think what really confuses things (me and perhaps other casual users) is that on Github, PerditionC appears to be primary and there are many forks of it including FDOS, see https://github.com/FDOS/kernel/network/members. I'm not sure if anything can be done about that globally, I personally deleted my fork of PerditionC and reforked from FDOS to get the graphic looking right.

**Comment by stsp** [comment]
> I'm not sure if anything can be done about that globally

IMHO you can just unfork FDOS (and give up on the rest).

> deleted my fork of PerditionC and reforked from FDOS to get the graphic looking right.

Well, if he is serious about the re-sync, I wouldn't
delete it. :)

**Comment by andrewbird** [comment]
I really do believe FDOS is primary as there are other regular contributors to it too, and as Bart pointed out earlier the github description makes this clear. The PerditionC repo is a historical artefact which wouldn't confuse in itself except that the github graphic I linked to earlier depicts it as primary, that's the only point I was trying to make. There are new commits in its master that probably belong in a topic branch, which adds to the illusion.

**Comment by PerditionC** [comment]
FDOS is the primary.  I had looked at one point in the past, there was no way to promote it to look like the main fork.  Deleting my original from PerditionC from the docs would promote a random fork to look like the primary one.  I use PerditionC one for my development instead of a feature branch because I have hard enough time remembering what it is I am doing when I get time to work on it, I don't need to also guess which branch it was.

**Comment by andrewbird** [comment]
Thanks for the explanation, I won't hassle you any more except to say that on the times I've needed to speak to github support they've been extremely helpful and responsive; perhaps they can suggest a solution?

**Comment by bartoldeman** [comment]
I know a way.. but I'll get back in 6 hours to explain it.

**Comment by bartoldeman** [comment]
@PerditionC the only way to do this somewhat properly is to transfer the PerditionC/fdkernel repository to FDOS . However you must first move https://github.com/FDOS/kernel somewhere else (e.g. to my account) otherwise that won't work. So that would mean:
1. in https://github.com/FDOS/kernel/settings, go to "Danger Zone", then click on "Transfer", transfer to bartoldeman.
2. in https://github.com/PerditionC/fdkernel/settings, go to "Danger Zone", then click on "Transfer" and move to FDOS.

 Once that is done the transferred repo's git can be changed to match the current FDOS/kernel state, with the current PerditionC states as separate branches (I can do that too once the transfer is done).

The only trouble with this is that all the issues and PRs get moved too but at least the fork hierarchy will look more natural.

**Comment by stsp** [comment]
I unforked my repositories by simply
writing to github support. Yes, not the
most convenient way, but works.
They are probably a morons to still not
add a button for that for us, but they
have such button for sure.
